// Code generated by ent, DO NOT EDIT.

package announcement

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the announcement type in the database.
	Label = "announcement"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSiteID holds the string denoting the site_id field in the database.
	FieldSiteID = "site_id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldFingerprint holds the string denoting the fingerprint field in the database.
	FieldFingerprint = "fingerprint"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldExtra holds the string denoting the extra field in the database.
	FieldExtra = "extra"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldFirstSeenAt holds the string denoting the first_seen_at field in the database.
	FieldFirstSeenAt = "first_seen_at"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// FieldReadAt holds the string denoting the read_at field in the database.
	FieldReadAt = "read_at"
	// EdgeSite holds the string denoting the site edge name in mutations.
	EdgeSite = "site"
	// Table holds the table name of the announcement in the database.
	Table = "announcements"
	// SiteTable is the table that holds the site relation/edge.
	SiteTable = "announcements"
	// SiteInverseTable is the table name for the Site entity.
	// It exists in this package in order to avoid circular dependency with the "site" package.
	SiteInverseTable = "sites"
	// SiteColumn is the table column denoting the site relation/edge.
	SiteColumn = "site_id"
)

// Columns holds all SQL columns for announcement fields.
var Columns = []string{
	FieldID,
	FieldSiteID,
	FieldSource,
	FieldFingerprint,
	FieldContent,
	FieldKind,
	FieldExtra,
	FieldPublishedAt,
	FieldFirstSeenAt,
	FieldLastSeenAt,
	FieldReadAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultKind holds the default value on creation for the "kind" field.
	DefaultKind string
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
)

// Source defines the type for the "source" enum field.
type Source string

// Source values.
const (
	SourceStatus Source = "status"
	SourceNotice Source = "notice"
)

func (s Source) String() string {
	return string(s)
}

// SourceValidator is a validator for the "source" field enum values. It is called by the builders before save.
func SourceValidator(s Source) error {
	switch s {
	case SourceStatus, SourceNotice:
		return nil
	default:
		return fmt.Errorf("announcement: invalid enum value for source field: %q", s)
	}
}

// OrderOption defines the ordering options for the Announcement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySiteID orders the results by the site_id field.
func BySiteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSiteID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByFingerprint orders the results by the fingerprint field.
func ByFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFingerprint, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByExtra orders the results by the extra field.
func ByExtra(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtra, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByFirstSeenAt orders the results by the first_seen_at field.
func ByFirstSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstSeenAt, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByReadAt orders the results by the read_at field.
func ByReadAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReadAt, opts...).ToFunc()
}

// BySiteField orders the results by site field.
func BySiteField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSiteStep(), sql.OrderByField(field, opts...))
	}
}
func newSiteStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SiteInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SiteTable, SiteColumn),
	)
}
