// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elykia/apihub/server/ent/announcement"
	"github.com/elykia/apihub/server/ent/site"
)

// AnnouncementCreate is the builder for creating a Announcement entity.
type AnnouncementCreate struct {
	config
	mutation *AnnouncementMutation
	hooks    []Hook
}

// SetSiteID sets the "site_id" field.
func (_c *AnnouncementCreate) SetSiteID(v string) *AnnouncementCreate {
	_c.mutation.SetSiteID(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *AnnouncementCreate) SetSource(v announcement.Source) *AnnouncementCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetFingerprint sets the "fingerprint" field.
func (_c *AnnouncementCreate) SetFingerprint(v string) *AnnouncementCreate {
	_c.mutation.SetFingerprint(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *AnnouncementCreate) SetContent(v string) *AnnouncementCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *AnnouncementCreate) SetKind(v string) *AnnouncementCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *AnnouncementCreate) SetNillableKind(v *string) *AnnouncementCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetExtra sets the "extra" field.
func (_c *AnnouncementCreate) SetExtra(v string) *AnnouncementCreate {
	_c.mutation.SetExtra(v)
	return _c
}

// SetNillableExtra sets the "extra" field if the given value is not nil.
func (_c *AnnouncementCreate) SetNillableExtra(v *string) *AnnouncementCreate {
	if v != nil {
		_c.SetExtra(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *AnnouncementCreate) SetPublishedAt(v time.Time) *AnnouncementCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *AnnouncementCreate) SetNillablePublishedAt(v *time.Time) *AnnouncementCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_c *AnnouncementCreate) SetFirstSeenAt(v time.Time) *AnnouncementCreate {
	_c.mutation.SetFirstSeenAt(v)
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *AnnouncementCreate) SetLastSeenAt(v time.Time) *AnnouncementCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetReadAt sets the "read_at" field.
func (_c *AnnouncementCreate) SetReadAt(v time.Time) *AnnouncementCreate {
	_c.mutation.SetReadAt(v)
	return _c
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_c *AnnouncementCreate) SetNillableReadAt(v *time.Time) *AnnouncementCreate {
	if v != nil {
		_c.SetReadAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AnnouncementCreate) SetID(v string) *AnnouncementCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSite sets the "site" edge to the Site entity.
func (_c *AnnouncementCreate) SetSite(v *Site) *AnnouncementCreate {
	return _c.SetSiteID(v.ID)
}

// Mutation returns the AnnouncementMutation object of the builder.
func (_c *AnnouncementCreate) Mutation() *AnnouncementMutation {
	return _c.mutation
}

// Save creates the Announcement in the database.
func (_c *AnnouncementCreate) Save(ctx context.Context) (*Announcement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AnnouncementCreate) SaveX(ctx context.Context) *Announcement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnnouncementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnnouncementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AnnouncementCreate) defaults() {
	if _, ok := _c.mutation.Kind(); !ok {
		v := announcement.DefaultKind
		_c.mutation.SetKind(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AnnouncementCreate) check() error {
	if _, ok := _c.mutation.SiteID(); !ok {
		return &ValidationError{Name: "site_id", err: errors.New(`ent: missing required field "Announcement.site_id"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Announcement.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := announcement.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Announcement.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Fingerprint(); !ok {
		return &ValidationError{Name: "fingerprint", err: errors.New(`ent: missing required field "Announcement.fingerprint"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Announcement.content"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Announcement.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := announcement.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Announcement.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FirstSeenAt(); !ok {
		return &ValidationError{Name: "first_seen_at", err: errors.New(`ent: missing required field "Announcement.first_seen_at"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "Announcement.last_seen_at"`)}
	}
	if len(_c.mutation.SiteIDs()) == 0 {
		return &ValidationError{Name: "site", err: errors.New(`ent: missing required edge "Announcement.site"`)}
	}
	return nil
}

func (_c *AnnouncementCreate) sqlSave(ctx context.Context) (*Announcement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Announcement.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AnnouncementCreate) createSpec() (*Announcement, *sqlgraph.CreateSpec) {
	var (
		_node = &Announcement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(announcement.Table, sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(announcement.FieldSource, field.TypeEnum, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Fingerprint(); ok {
		_spec.SetField(announcement.FieldFingerprint, field.TypeString, value)
		_node.Fingerprint = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(announcement.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(announcement.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Extra(); ok {
		_spec.SetField(announcement.FieldExtra, field.TypeString, value)
		_node.Extra = &value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(announcement.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.FirstSeenAt(); ok {
		_spec.SetField(announcement.FieldFirstSeenAt, field.TypeTime, value)
		_node.FirstSeenAt = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(announcement.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.ReadAt(); ok {
		_spec.SetField(announcement.FieldReadAt, field.TypeTime, value)
		_node.ReadAt = &value
	}
	if nodes := _c.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcement.SiteTable,
			Columns: []string{announcement.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SiteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AnnouncementCreateBulk is the builder for creating many Announcement entities in bulk.
type AnnouncementCreateBulk struct {
	config
	err      error
	builders []*AnnouncementCreate
}

// Save creates the Announcement entities in the database.
func (_c *AnnouncementCreateBulk) Save(ctx context.Context) ([]*Announcement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Announcement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnnouncementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AnnouncementCreateBulk) SaveX(ctx context.Context) []*Announcement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnnouncementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnnouncementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
