// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elykia/apihub/server/ent/announcement"
	"github.com/elykia/apihub/server/ent/predicate"
)

// AnnouncementUpdate is the builder for updating Announcement entities.
type AnnouncementUpdate struct {
	config
	hooks    []Hook
	mutation *AnnouncementMutation
}

// Where appends a list predicates to the AnnouncementUpdate builder.
func (_u *AnnouncementUpdate) Where(ps ...predicate.Announcement) *AnnouncementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSource sets the "source" field.
func (_u *AnnouncementUpdate) SetSource(v announcement.Source) *AnnouncementUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableSource(v *announcement.Source) *AnnouncementUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *AnnouncementUpdate) SetFingerprint(v string) *AnnouncementUpdate {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableFingerprint(v *string) *AnnouncementUpdate {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *AnnouncementUpdate) SetContent(v string) *AnnouncementUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableContent(v *string) *AnnouncementUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *AnnouncementUpdate) SetKind(v string) *AnnouncementUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableKind(v *string) *AnnouncementUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetExtra sets the "extra" field.
func (_u *AnnouncementUpdate) SetExtra(v string) *AnnouncementUpdate {
	_u.mutation.SetExtra(v)
	return _u
}

// SetNillableExtra sets the "extra" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableExtra(v *string) *AnnouncementUpdate {
	if v != nil {
		_u.SetExtra(*v)
	}
	return _u
}

// ClearExtra clears the value of the "extra" field.
func (_u *AnnouncementUpdate) ClearExtra() *AnnouncementUpdate {
	_u.mutation.ClearExtra()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *AnnouncementUpdate) SetPublishedAt(v time.Time) *AnnouncementUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillablePublishedAt(v *time.Time) *AnnouncementUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *AnnouncementUpdate) ClearPublishedAt() *AnnouncementUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *AnnouncementUpdate) SetLastSeenAt(v time.Time) *AnnouncementUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableLastSeenAt(v *time.Time) *AnnouncementUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *AnnouncementUpdate) SetReadAt(v time.Time) *AnnouncementUpdate {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableReadAt(v *time.Time) *AnnouncementUpdate {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// ClearReadAt clears the value of the "read_at" field.
func (_u *AnnouncementUpdate) ClearReadAt() *AnnouncementUpdate {
	_u.mutation.ClearReadAt()
	return _u
}

// Mutation returns the AnnouncementMutation object of the builder.
func (_u *AnnouncementUpdate) Mutation() *AnnouncementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnnouncementUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnnouncementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := announcement.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Announcement.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := announcement.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Announcement.kind": %w`, err)}
		}
	}
	if _u.mutation.SiteCleared() && len(_u.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Announcement.site"`)
	}
	return nil
}

func (_u *AnnouncementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcement.Table, announcement.Columns, sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(announcement.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(announcement.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(announcement.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(announcement.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Extra(); ok {
		_spec.SetField(announcement.FieldExtra, field.TypeString, value)
	}
	if _u.mutation.ExtraCleared() {
		_spec.ClearField(announcement.FieldExtra, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(announcement.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(announcement.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(announcement.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(announcement.FieldReadAt, field.TypeTime, value)
	}
	if _u.mutation.ReadAtCleared() {
		_spec.ClearField(announcement.FieldReadAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnnouncementUpdateOne is the builder for updating a single Announcement entity.
type AnnouncementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnnouncementMutation
}

// SetSource sets the "source" field.
func (_u *AnnouncementUpdateOne) SetSource(v announcement.Source) *AnnouncementUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableSource(v *announcement.Source) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *AnnouncementUpdateOne) SetFingerprint(v string) *AnnouncementUpdateOne {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableFingerprint(v *string) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *AnnouncementUpdateOne) SetContent(v string) *AnnouncementUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableContent(v *string) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *AnnouncementUpdateOne) SetKind(v string) *AnnouncementUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableKind(v *string) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetExtra sets the "extra" field.
func (_u *AnnouncementUpdateOne) SetExtra(v string) *AnnouncementUpdateOne {
	_u.mutation.SetExtra(v)
	return _u
}

// SetNillableExtra sets the "extra" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableExtra(v *string) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetExtra(*v)
	}
	return _u
}

// ClearExtra clears the value of the "extra" field.
func (_u *AnnouncementUpdateOne) ClearExtra() *AnnouncementUpdateOne {
	_u.mutation.ClearExtra()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *AnnouncementUpdateOne) SetPublishedAt(v time.Time) *AnnouncementUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillablePublishedAt(v *time.Time) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *AnnouncementUpdateOne) ClearPublishedAt() *AnnouncementUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *AnnouncementUpdateOne) SetLastSeenAt(v time.Time) *AnnouncementUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableLastSeenAt(v *time.Time) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *AnnouncementUpdateOne) SetReadAt(v time.Time) *AnnouncementUpdateOne {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableReadAt(v *time.Time) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// ClearReadAt clears the value of the "read_at" field.
func (_u *AnnouncementUpdateOne) ClearReadAt() *AnnouncementUpdateOne {
	_u.mutation.ClearReadAt()
	return _u
}

// Mutation returns the AnnouncementMutation object of the builder.
func (_u *AnnouncementUpdateOne) Mutation() *AnnouncementMutation {
	return _u.mutation
}

// Where appends a list predicates to the AnnouncementUpdate builder.
func (_u *AnnouncementUpdateOne) Where(ps ...predicate.Announcement) *AnnouncementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnnouncementUpdateOne) Select(field string, fields ...string) *AnnouncementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Announcement entity.
func (_u *AnnouncementUpdateOne) Save(ctx context.Context) (*Announcement, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementUpdateOne) SaveX(ctx context.Context) *Announcement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnnouncementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := announcement.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Announcement.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := announcement.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Announcement.kind": %w`, err)}
		}
	}
	if _u.mutation.SiteCleared() && len(_u.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Announcement.site"`)
	}
	return nil
}

func (_u *AnnouncementUpdateOne) sqlSave(ctx context.Context) (_node *Announcement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcement.Table, announcement.Columns, sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Announcement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, announcement.FieldID)
		for _, f := range fields {
			if !announcement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != announcement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(announcement.FieldSource, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(announcement.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(announcement.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(announcement.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Extra(); ok {
		_spec.SetField(announcement.FieldExtra, field.TypeString, value)
	}
	if _u.mutation.ExtraCleared() {
		_spec.ClearField(announcement.FieldExtra, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(announcement.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(announcement.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(announcement.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(announcement.FieldReadAt, field.TypeTime, value)
	}
	if _u.mutation.ReadAtCleared() {
		_spec.ClearField(announcement.FieldReadAt, field.TypeTime)
	}
	_node = &Announcement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
