// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/elykia/apihub/server/ent/announcementsyncrun"
	"github.com/elykia/apihub/server/ent/site"
)

// AnnouncementSyncRun is the model entity for the AnnouncementSyncRun schema.
type AnnouncementSyncRun struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// SiteID holds the value of the "site_id" field.
	SiteID string `json:"site_id,omitempty"`
	// Status holds the value of the "status" field.
	Status announcementsyncrun.Status `json:"status,omitempty"`
	// AddedCount holds the value of the "added_count" field.
	AddedCount int `json:"added_count,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AnnouncementSyncRunQuery when eager-loading is set.
	Edges        AnnouncementSyncRunEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AnnouncementSyncRunEdges holds the relations/edges for other nodes in the graph.
type AnnouncementSyncRunEdges struct {
	// Site holds the value of the site edge.
	Site *Site `json:"site,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SiteOrErr returns the Site value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AnnouncementSyncRunEdges) SiteOrErr() (*Site, error) {
	if e.Site != nil {
		return e.Site, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: site.Label}
	}
	return nil, &NotLoadedError{edge: "site"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AnnouncementSyncRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case announcementsyncrun.FieldAddedCount:
			values[i] = new(sql.NullInt64)
		case announcementsyncrun.FieldID, announcementsyncrun.FieldSiteID, announcementsyncrun.FieldStatus, announcementsyncrun.FieldMessage, announcementsyncrun.FieldRequestID:
			values[i] = new(sql.NullString)
		case announcementsyncrun.FieldStartedAt, announcementsyncrun.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AnnouncementSyncRun fields.
func (_m *AnnouncementSyncRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case announcementsyncrun.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case announcementsyncrun.FieldSiteID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field site_id", values[i])
			} else if value.Valid {
				_m.SiteID = value.String
			}
		case announcementsyncrun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = announcementsyncrun.Status(value.String)
			}
		case announcementsyncrun.FieldAddedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field added_count", values[i])
			} else if value.Valid {
				_m.AddedCount = int(value.Int64)
			}
		case announcementsyncrun.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case announcementsyncrun.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case announcementsyncrun.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case announcementsyncrun.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AnnouncementSyncRun.
// This includes values selected through modifiers, order, etc.
func (_m *AnnouncementSyncRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySite queries the "site" edge of the AnnouncementSyncRun entity.
func (_m *AnnouncementSyncRun) QuerySite() *SiteQuery {
	return NewAnnouncementSyncRunClient(_m.config).QuerySite(_m)
}

// Update returns a builder for updating this AnnouncementSyncRun.
// Note that you need to call AnnouncementSyncRun.Unwrap() before calling this method if this AnnouncementSyncRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AnnouncementSyncRun) Update() *AnnouncementSyncRunUpdateOne {
	return NewAnnouncementSyncRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AnnouncementSyncRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AnnouncementSyncRun) Unwrap() *AnnouncementSyncRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AnnouncementSyncRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AnnouncementSyncRun) String() string {
	var builder strings.Builder
	builder.WriteString("AnnouncementSyncRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("site_id=")
	builder.WriteString(_m.SiteID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("added_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AddedCount))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteByte(')')
	return builder.String()
}

// AnnouncementSyncRuns is a parsable slice of AnnouncementSyncRun.
type AnnouncementSyncRuns []*AnnouncementSyncRun
