// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elykia/apihub/server/ent/announcementsyncrun"
	"github.com/elykia/apihub/server/ent/site"
)

// AnnouncementSyncRunCreate is the builder for creating a AnnouncementSyncRun entity.
type AnnouncementSyncRunCreate struct {
	config
	mutation *AnnouncementSyncRunMutation
	hooks    []Hook
}

// SetSiteID sets the "site_id" field.
func (_c *AnnouncementSyncRunCreate) SetSiteID(v string) *AnnouncementSyncRunCreate {
	_c.mutation.SetSiteID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AnnouncementSyncRunCreate) SetStatus(v announcementsyncrun.Status) *AnnouncementSyncRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetAddedCount sets the "added_count" field.
func (_c *AnnouncementSyncRunCreate) SetAddedCount(v int) *AnnouncementSyncRunCreate {
	_c.mutation.SetAddedCount(v)
	return _c
}

// SetNillableAddedCount sets the "added_count" field if the given value is not nil.
func (_c *AnnouncementSyncRunCreate) SetNillableAddedCount(v *int) *AnnouncementSyncRunCreate {
	if v != nil {
		_c.SetAddedCount(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *AnnouncementSyncRunCreate) SetMessage(v string) *AnnouncementSyncRunCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *AnnouncementSyncRunCreate) SetNillableMessage(v *string) *AnnouncementSyncRunCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *AnnouncementSyncRunCreate) SetStartedAt(v time.Time) *AnnouncementSyncRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *AnnouncementSyncRunCreate) SetFinishedAt(v time.Time) *AnnouncementSyncRunCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *AnnouncementSyncRunCreate) SetNillableFinishedAt(v *time.Time) *AnnouncementSyncRunCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *AnnouncementSyncRunCreate) SetRequestID(v string) *AnnouncementSyncRunCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AnnouncementSyncRunCreate) SetID(v string) *AnnouncementSyncRunCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSite sets the "site" edge to the Site entity.
func (_c *AnnouncementSyncRunCreate) SetSite(v *Site) *AnnouncementSyncRunCreate {
	return _c.SetSiteID(v.ID)
}

// Mutation returns the AnnouncementSyncRunMutation object of the builder.
func (_c *AnnouncementSyncRunCreate) Mutation() *AnnouncementSyncRunMutation {
	return _c.mutation
}

// Save creates the AnnouncementSyncRun in the database.
func (_c *AnnouncementSyncRunCreate) Save(ctx context.Context) (*AnnouncementSyncRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AnnouncementSyncRunCreate) SaveX(ctx context.Context) *AnnouncementSyncRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnnouncementSyncRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnnouncementSyncRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AnnouncementSyncRunCreate) defaults() {
	if _, ok := _c.mutation.AddedCount(); !ok {
		v := announcementsyncrun.DefaultAddedCount
		_c.mutation.SetAddedCount(v)
	}
	if _, ok := _c.mutation.Message(); !ok {
		v := announcementsyncrun.DefaultMessage
		_c.mutation.SetMessage(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AnnouncementSyncRunCreate) check() error {
	if _, ok := _c.mutation.SiteID(); !ok {
		return &ValidationError{Name: "site_id", err: errors.New(`ent: missing required field "AnnouncementSyncRun.site_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AnnouncementSyncRun.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := announcementsyncrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AnnouncementSyncRun.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AddedCount(); !ok {
		return &ValidationError{Name: "added_count", err: errors.New(`ent: missing required field "AnnouncementSyncRun.added_count"`)}
	}
	if v, ok := _c.mutation.AddedCount(); ok {
		if err := announcementsyncrun.AddedCountValidator(v); err != nil {
			return &ValidationError{Name: "added_count", err: fmt.Errorf(`ent: validator failed for field "AnnouncementSyncRun.added_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "AnnouncementSyncRun.message"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "AnnouncementSyncRun.started_at"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "AnnouncementSyncRun.request_id"`)}
	}
	if len(_c.mutation.SiteIDs()) == 0 {
		return &ValidationError{Name: "site", err: errors.New(`ent: missing required edge "AnnouncementSyncRun.site"`)}
	}
	return nil
}

func (_c *AnnouncementSyncRunCreate) sqlSave(ctx context.Context) (*AnnouncementSyncRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AnnouncementSyncRun.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AnnouncementSyncRunCreate) createSpec() (*AnnouncementSyncRun, *sqlgraph.CreateSpec) {
	var (
		_node = &AnnouncementSyncRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(announcementsyncrun.Table, sqlgraph.NewFieldSpec(announcementsyncrun.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(announcementsyncrun.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AddedCount(); ok {
		_spec.SetField(announcementsyncrun.FieldAddedCount, field.TypeInt, value)
		_node.AddedCount = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(announcementsyncrun.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(announcementsyncrun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(announcementsyncrun.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(announcementsyncrun.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if nodes := _c.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   announcementsyncrun.SiteTable,
			Columns: []string{announcementsyncrun.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SiteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AnnouncementSyncRunCreateBulk is the builder for creating many AnnouncementSyncRun entities in bulk.
type AnnouncementSyncRunCreateBulk struct {
	config
	err      error
	builders []*AnnouncementSyncRunCreate
}

// Save creates the AnnouncementSyncRun entities in the database.
func (_c *AnnouncementSyncRunCreateBulk) Save(ctx context.Context) ([]*AnnouncementSyncRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AnnouncementSyncRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnnouncementSyncRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AnnouncementSyncRunCreateBulk) SaveX(ctx context.Context) []*AnnouncementSyncRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnnouncementSyncRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnnouncementSyncRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
