// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elykia/apihub/server/ent/announcementsyncrun"
	"github.com/elykia/apihub/server/ent/predicate"
)

// AnnouncementSyncRunUpdate is the builder for updating AnnouncementSyncRun entities.
type AnnouncementSyncRunUpdate struct {
	config
	hooks    []Hook
	mutation *AnnouncementSyncRunMutation
}

// Where appends a list predicates to the AnnouncementSyncRunUpdate builder.
func (_u *AnnouncementSyncRunUpdate) Where(ps ...predicate.AnnouncementSyncRun) *AnnouncementSyncRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AnnouncementSyncRunUpdate) SetStatus(v announcementsyncrun.Status) *AnnouncementSyncRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AnnouncementSyncRunUpdate) SetNillableStatus(v *announcementsyncrun.Status) *AnnouncementSyncRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAddedCount sets the "added_count" field.
func (_u *AnnouncementSyncRunUpdate) SetAddedCount(v int) *AnnouncementSyncRunUpdate {
	_u.mutation.ResetAddedCount()
	_u.mutation.SetAddedCount(v)
	return _u
}

// SetNillableAddedCount sets the "added_count" field if the given value is not nil.
func (_u *AnnouncementSyncRunUpdate) SetNillableAddedCount(v *int) *AnnouncementSyncRunUpdate {
	if v != nil {
		_u.SetAddedCount(*v)
	}
	return _u
}

// AddAddedCount adds value to the "added_count" field.
func (_u *AnnouncementSyncRunUpdate) AddAddedCount(v int) *AnnouncementSyncRunUpdate {
	_u.mutation.AddAddedCount(v)
	return _u
}

// SetMessage sets the "message" field.
func (_u *AnnouncementSyncRunUpdate) SetMessage(v string) *AnnouncementSyncRunUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *AnnouncementSyncRunUpdate) SetNillableMessage(v *string) *AnnouncementSyncRunUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *AnnouncementSyncRunUpdate) SetStartedAt(v time.Time) *AnnouncementSyncRunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *AnnouncementSyncRunUpdate) SetNillableStartedAt(v *time.Time) *AnnouncementSyncRunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *AnnouncementSyncRunUpdate) SetFinishedAt(v time.Time) *AnnouncementSyncRunUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *AnnouncementSyncRunUpdate) SetNillableFinishedAt(v *time.Time) *AnnouncementSyncRunUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *AnnouncementSyncRunUpdate) ClearFinishedAt() *AnnouncementSyncRunUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AnnouncementSyncRunUpdate) SetRequestID(v string) *AnnouncementSyncRunUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AnnouncementSyncRunUpdate) SetNillableRequestID(v *string) *AnnouncementSyncRunUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// Mutation returns the AnnouncementSyncRunMutation object of the builder.
func (_u *AnnouncementSyncRunUpdate) Mutation() *AnnouncementSyncRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnnouncementSyncRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementSyncRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnnouncementSyncRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementSyncRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementSyncRunUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := announcementsyncrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AnnouncementSyncRun.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AddedCount(); ok {
		if err := announcementsyncrun.AddedCountValidator(v); err != nil {
			return &ValidationError{Name: "added_count", err: fmt.Errorf(`ent: validator failed for field "AnnouncementSyncRun.added_count": %w`, err)}
		}
	}
	if _u.mutation.SiteCleared() && len(_u.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AnnouncementSyncRun.site"`)
	}
	return nil
}

func (_u *AnnouncementSyncRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcementsyncrun.Table, announcementsyncrun.Columns, sqlgraph.NewFieldSpec(announcementsyncrun.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(announcementsyncrun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.SetField(announcementsyncrun.FieldAddedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAddedCount(); ok {
		_spec.AddField(announcementsyncrun.FieldAddedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(announcementsyncrun.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(announcementsyncrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(announcementsyncrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(announcementsyncrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(announcementsyncrun.FieldRequestID, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcementsyncrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnnouncementSyncRunUpdateOne is the builder for updating a single AnnouncementSyncRun entity.
type AnnouncementSyncRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnnouncementSyncRunMutation
}

// SetStatus sets the "status" field.
func (_u *AnnouncementSyncRunUpdateOne) SetStatus(v announcementsyncrun.Status) *AnnouncementSyncRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AnnouncementSyncRunUpdateOne) SetNillableStatus(v *announcementsyncrun.Status) *AnnouncementSyncRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAddedCount sets the "added_count" field.
func (_u *AnnouncementSyncRunUpdateOne) SetAddedCount(v int) *AnnouncementSyncRunUpdateOne {
	_u.mutation.ResetAddedCount()
	_u.mutation.SetAddedCount(v)
	return _u
}

// SetNillableAddedCount sets the "added_count" field if the given value is not nil.
func (_u *AnnouncementSyncRunUpdateOne) SetNillableAddedCount(v *int) *AnnouncementSyncRunUpdateOne {
	if v != nil {
		_u.SetAddedCount(*v)
	}
	return _u
}

// AddAddedCount adds value to the "added_count" field.
func (_u *AnnouncementSyncRunUpdateOne) AddAddedCount(v int) *AnnouncementSyncRunUpdateOne {
	_u.mutation.AddAddedCount(v)
	return _u
}

// SetMessage sets the "message" field.
func (_u *AnnouncementSyncRunUpdateOne) SetMessage(v string) *AnnouncementSyncRunUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *AnnouncementSyncRunUpdateOne) SetNillableMessage(v *string) *AnnouncementSyncRunUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *AnnouncementSyncRunUpdateOne) SetStartedAt(v time.Time) *AnnouncementSyncRunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *AnnouncementSyncRunUpdateOne) SetNillableStartedAt(v *time.Time) *AnnouncementSyncRunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *AnnouncementSyncRunUpdateOne) SetFinishedAt(v time.Time) *AnnouncementSyncRunUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *AnnouncementSyncRunUpdateOne) SetNillableFinishedAt(v *time.Time) *AnnouncementSyncRunUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *AnnouncementSyncRunUpdateOne) ClearFinishedAt() *AnnouncementSyncRunUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AnnouncementSyncRunUpdateOne) SetRequestID(v string) *AnnouncementSyncRunUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AnnouncementSyncRunUpdateOne) SetNillableRequestID(v *string) *AnnouncementSyncRunUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// Mutation returns the AnnouncementSyncRunMutation object of the builder.
func (_u *AnnouncementSyncRunUpdateOne) Mutation() *AnnouncementSyncRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the AnnouncementSyncRunUpdate builder.
func (_u *AnnouncementSyncRunUpdateOne) Where(ps ...predicate.AnnouncementSyncRun) *AnnouncementSyncRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnnouncementSyncRunUpdateOne) Select(field string, fields ...string) *AnnouncementSyncRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AnnouncementSyncRun entity.
func (_u *AnnouncementSyncRunUpdateOne) Save(ctx context.Context) (*AnnouncementSyncRun, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementSyncRunUpdateOne) SaveX(ctx context.Context) *AnnouncementSyncRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnnouncementSyncRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementSyncRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementSyncRunUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := announcementsyncrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AnnouncementSyncRun.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AddedCount(); ok {
		if err := announcementsyncrun.AddedCountValidator(v); err != nil {
			return &ValidationError{Name: "added_count", err: fmt.Errorf(`ent: validator failed for field "AnnouncementSyncRun.added_count": %w`, err)}
		}
	}
	if _u.mutation.SiteCleared() && len(_u.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AnnouncementSyncRun.site"`)
	}
	return nil
}

func (_u *AnnouncementSyncRunUpdateOne) sqlSave(ctx context.Context) (_node *AnnouncementSyncRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcementsyncrun.Table, announcementsyncrun.Columns, sqlgraph.NewFieldSpec(announcementsyncrun.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AnnouncementSyncRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, announcementsyncrun.FieldID)
		for _, f := range fields {
			if !announcementsyncrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != announcementsyncrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(announcementsyncrun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AddedCount(); ok {
		_spec.SetField(announcementsyncrun.FieldAddedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAddedCount(); ok {
		_spec.AddField(announcementsyncrun.FieldAddedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(announcementsyncrun.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(announcementsyncrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(announcementsyncrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(announcementsyncrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(announcementsyncrun.FieldRequestID, field.TypeString, value)
	}
	_node = &AnnouncementSyncRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcementsyncrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
