// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elykia/apihub/server/ent/announcementsyncrun"
	"github.com/elykia/apihub/server/ent/predicate"
)

// AnnouncementSyncRunDelete is the builder for deleting a AnnouncementSyncRun entity.
type AnnouncementSyncRunDelete struct {
	config
	hooks    []Hook
	mutation *AnnouncementSyncRunMutation
}

// Where appends a list predicates to the AnnouncementSyncRunDelete builder.
func (_d *AnnouncementSyncRunDelete) Where(ps ...predicate.AnnouncementSyncRun) *AnnouncementSyncRunDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AnnouncementSyncRunDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AnnouncementSyncRunDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AnnouncementSyncRunDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(announcementsyncrun.Table, sqlgraph.NewFieldSpec(announcementsyncrun.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AnnouncementSyncRunDeleteOne is the builder for deleting a single AnnouncementSyncRun entity.
type AnnouncementSyncRunDeleteOne struct {
	_d *AnnouncementSyncRunDelete
}

// Where appends a list predicates to the AnnouncementSyncRunDelete builder.
func (_d *AnnouncementSyncRunDeleteOne) Where(ps ...predicate.AnnouncementSyncRun) *AnnouncementSyncRunDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AnnouncementSyncRunDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{announcementsyncrun.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AnnouncementSyncRunDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
