// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elykia/apihub/server/ent/checkinrun"
	"github.com/elykia/apihub/server/ent/site"
)

// CheckinRunCreate is the builder for creating a CheckinRun entity.
type CheckinRunCreate struct {
	config
	mutation *CheckinRunMutation
	hooks    []Hook
}

// SetSiteID sets the "site_id" field.
func (_c *CheckinRunCreate) SetSiteID(v string) *CheckinRunCreate {
	_c.mutation.SetSiteID(v)
	return _c
}

// SetLocalDate sets the "local_date" field.
func (_c *CheckinRunCreate) SetLocalDate(v time.Time) *CheckinRunCreate {
	_c.mutation.SetLocalDate(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *CheckinRunCreate) SetStatus(v checkinrun.Status) *CheckinRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetRewardValue sets the "reward_value" field.
func (_c *CheckinRunCreate) SetRewardValue(v int64) *CheckinRunCreate {
	_c.mutation.SetRewardValue(v)
	return _c
}

// SetNillableRewardValue sets the "reward_value" field if the given value is not nil.
func (_c *CheckinRunCreate) SetNillableRewardValue(v *int64) *CheckinRunCreate {
	if v != nil {
		_c.SetRewardValue(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *CheckinRunCreate) SetMessage(v string) *CheckinRunCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *CheckinRunCreate) SetNillableMessage(v *string) *CheckinRunCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *CheckinRunCreate) SetErrorCode(v string) *CheckinRunCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *CheckinRunCreate) SetNillableErrorCode(v *string) *CheckinRunCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetAttemptCount sets the "attempt_count" field.
func (_c *CheckinRunCreate) SetAttemptCount(v int) *CheckinRunCreate {
	_c.mutation.SetAttemptCount(v)
	return _c
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_c *CheckinRunCreate) SetNillableAttemptCount(v *int) *CheckinRunCreate {
	if v != nil {
		_c.SetAttemptCount(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *CheckinRunCreate) SetStartedAt(v time.Time) *CheckinRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *CheckinRunCreate) SetFinishedAt(v time.Time) *CheckinRunCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *CheckinRunCreate) SetNillableFinishedAt(v *time.Time) *CheckinRunCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *CheckinRunCreate) SetRequestID(v string) *CheckinRunCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CheckinRunCreate) SetID(v string) *CheckinRunCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSite sets the "site" edge to the Site entity.
func (_c *CheckinRunCreate) SetSite(v *Site) *CheckinRunCreate {
	return _c.SetSiteID(v.ID)
}

// Mutation returns the CheckinRunMutation object of the builder.
func (_c *CheckinRunCreate) Mutation() *CheckinRunMutation {
	return _c.mutation
}

// Save creates the CheckinRun in the database.
func (_c *CheckinRunCreate) Save(ctx context.Context) (*CheckinRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CheckinRunCreate) SaveX(ctx context.Context) *CheckinRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckinRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckinRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CheckinRunCreate) defaults() {
	if _, ok := _c.mutation.Message(); !ok {
		v := checkinrun.DefaultMessage
		_c.mutation.SetMessage(v)
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		v := checkinrun.DefaultAttemptCount
		_c.mutation.SetAttemptCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CheckinRunCreate) check() error {
	if _, ok := _c.mutation.SiteID(); !ok {
		return &ValidationError{Name: "site_id", err: errors.New(`ent: missing required field "CheckinRun.site_id"`)}
	}
	if _, ok := _c.mutation.LocalDate(); !ok {
		return &ValidationError{Name: "local_date", err: errors.New(`ent: missing required field "CheckinRun.local_date"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CheckinRun.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := checkinrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CheckinRun.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "CheckinRun.message"`)}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := checkinrun.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "CheckinRun.error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		return &ValidationError{Name: "attempt_count", err: errors.New(`ent: missing required field "CheckinRun.attempt_count"`)}
	}
	if v, ok := _c.mutation.AttemptCount(); ok {
		if err := checkinrun.AttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "attempt_count", err: fmt.Errorf(`ent: validator failed for field "CheckinRun.attempt_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "CheckinRun.started_at"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "CheckinRun.request_id"`)}
	}
	if len(_c.mutation.SiteIDs()) == 0 {
		return &ValidationError{Name: "site", err: errors.New(`ent: missing required edge "CheckinRun.site"`)}
	}
	return nil
}

func (_c *CheckinRunCreate) sqlSave(ctx context.Context) (*CheckinRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CheckinRun.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CheckinRunCreate) createSpec() (*CheckinRun, *sqlgraph.CreateSpec) {
	var (
		_node = &CheckinRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(checkinrun.Table, sqlgraph.NewFieldSpec(checkinrun.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.LocalDate(); ok {
		_spec.SetField(checkinrun.FieldLocalDate, field.TypeTime, value)
		_node.LocalDate = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(checkinrun.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RewardValue(); ok {
		_spec.SetField(checkinrun.FieldRewardValue, field.TypeInt64, value)
		_node.RewardValue = &value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(checkinrun.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(checkinrun.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = &value
	}
	if value, ok := _c.mutation.AttemptCount(); ok {
		_spec.SetField(checkinrun.FieldAttemptCount, field.TypeInt, value)
		_node.AttemptCount = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(checkinrun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(checkinrun.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(checkinrun.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if nodes := _c.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkinrun.SiteTable,
			Columns: []string{checkinrun.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SiteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CheckinRunCreateBulk is the builder for creating many CheckinRun entities in bulk.
type CheckinRunCreateBulk struct {
	config
	err      error
	builders []*CheckinRunCreate
}

// Save creates the CheckinRun entities in the database.
func (_c *CheckinRunCreateBulk) Save(ctx context.Context) ([]*CheckinRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CheckinRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CheckinRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CheckinRunCreateBulk) SaveX(ctx context.Context) []*CheckinRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckinRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckinRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
