// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elykia/apihub/server/ent/checkinrun"
	"github.com/elykia/apihub/server/ent/predicate"
)

// CheckinRunUpdate is the builder for updating CheckinRun entities.
type CheckinRunUpdate struct {
	config
	hooks    []Hook
	mutation *CheckinRunMutation
}

// Where appends a list predicates to the CheckinRunUpdate builder.
func (_u *CheckinRunUpdate) Where(ps ...predicate.CheckinRun) *CheckinRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CheckinRunUpdate) SetStatus(v checkinrun.Status) *CheckinRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CheckinRunUpdate) SetNillableStatus(v *checkinrun.Status) *CheckinRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRewardValue sets the "reward_value" field.
func (_u *CheckinRunUpdate) SetRewardValue(v int64) *CheckinRunUpdate {
	_u.mutation.ResetRewardValue()
	_u.mutation.SetRewardValue(v)
	return _u
}

// SetNillableRewardValue sets the "reward_value" field if the given value is not nil.
func (_u *CheckinRunUpdate) SetNillableRewardValue(v *int64) *CheckinRunUpdate {
	if v != nil {
		_u.SetRewardValue(*v)
	}
	return _u
}

// AddRewardValue adds value to the "reward_value" field.
func (_u *CheckinRunUpdate) AddRewardValue(v int64) *CheckinRunUpdate {
	_u.mutation.AddRewardValue(v)
	return _u
}

// ClearRewardValue clears the value of the "reward_value" field.
func (_u *CheckinRunUpdate) ClearRewardValue() *CheckinRunUpdate {
	_u.mutation.ClearRewardValue()
	return _u
}

// SetMessage sets the "message" field.
func (_u *CheckinRunUpdate) SetMessage(v string) *CheckinRunUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *CheckinRunUpdate) SetNillableMessage(v *string) *CheckinRunUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *CheckinRunUpdate) SetErrorCode(v string) *CheckinRunUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *CheckinRunUpdate) SetNillableErrorCode(v *string) *CheckinRunUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *CheckinRunUpdate) ClearErrorCode() *CheckinRunUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *CheckinRunUpdate) SetAttemptCount(v int) *CheckinRunUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *CheckinRunUpdate) SetNillableAttemptCount(v *int) *CheckinRunUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *CheckinRunUpdate) AddAttemptCount(v int) *CheckinRunUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *CheckinRunUpdate) SetStartedAt(v time.Time) *CheckinRunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *CheckinRunUpdate) SetNillableStartedAt(v *time.Time) *CheckinRunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *CheckinRunUpdate) SetFinishedAt(v time.Time) *CheckinRunUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *CheckinRunUpdate) SetNillableFinishedAt(v *time.Time) *CheckinRunUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *CheckinRunUpdate) ClearFinishedAt() *CheckinRunUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *CheckinRunUpdate) SetRequestID(v string) *CheckinRunUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *CheckinRunUpdate) SetNillableRequestID(v *string) *CheckinRunUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// Mutation returns the CheckinRunMutation object of the builder.
func (_u *CheckinRunUpdate) Mutation() *CheckinRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CheckinRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckinRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CheckinRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckinRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckinRunUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := checkinrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CheckinRun.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := checkinrun.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "CheckinRun.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptCount(); ok {
		if err := checkinrun.AttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "attempt_count", err: fmt.Errorf(`ent: validator failed for field "CheckinRun.attempt_count": %w`, err)}
		}
	}
	if _u.mutation.SiteCleared() && len(_u.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CheckinRun.site"`)
	}
	return nil
}

func (_u *CheckinRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkinrun.Table, checkinrun.Columns, sqlgraph.NewFieldSpec(checkinrun.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(checkinrun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RewardValue(); ok {
		_spec.SetField(checkinrun.FieldRewardValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRewardValue(); ok {
		_spec.AddField(checkinrun.FieldRewardValue, field.TypeInt64, value)
	}
	if _u.mutation.RewardValueCleared() {
		_spec.ClearField(checkinrun.FieldRewardValue, field.TypeInt64)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(checkinrun.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(checkinrun.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(checkinrun.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(checkinrun.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(checkinrun.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(checkinrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(checkinrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(checkinrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(checkinrun.FieldRequestID, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkinrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CheckinRunUpdateOne is the builder for updating a single CheckinRun entity.
type CheckinRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CheckinRunMutation
}

// SetStatus sets the "status" field.
func (_u *CheckinRunUpdateOne) SetStatus(v checkinrun.Status) *CheckinRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CheckinRunUpdateOne) SetNillableStatus(v *checkinrun.Status) *CheckinRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRewardValue sets the "reward_value" field.
func (_u *CheckinRunUpdateOne) SetRewardValue(v int64) *CheckinRunUpdateOne {
	_u.mutation.ResetRewardValue()
	_u.mutation.SetRewardValue(v)
	return _u
}

// SetNillableRewardValue sets the "reward_value" field if the given value is not nil.
func (_u *CheckinRunUpdateOne) SetNillableRewardValue(v *int64) *CheckinRunUpdateOne {
	if v != nil {
		_u.SetRewardValue(*v)
	}
	return _u
}

// AddRewardValue adds value to the "reward_value" field.
func (_u *CheckinRunUpdateOne) AddRewardValue(v int64) *CheckinRunUpdateOne {
	_u.mutation.AddRewardValue(v)
	return _u
}

// ClearRewardValue clears the value of the "reward_value" field.
func (_u *CheckinRunUpdateOne) ClearRewardValue() *CheckinRunUpdateOne {
	_u.mutation.ClearRewardValue()
	return _u
}

// SetMessage sets the "message" field.
func (_u *CheckinRunUpdateOne) SetMessage(v string) *CheckinRunUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *CheckinRunUpdateOne) SetNillableMessage(v *string) *CheckinRunUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *CheckinRunUpdateOne) SetErrorCode(v string) *CheckinRunUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *CheckinRunUpdateOne) SetNillableErrorCode(v *string) *CheckinRunUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *CheckinRunUpdateOne) ClearErrorCode() *CheckinRunUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *CheckinRunUpdateOne) SetAttemptCount(v int) *CheckinRunUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *CheckinRunUpdateOne) SetNillableAttemptCount(v *int) *CheckinRunUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *CheckinRunUpdateOne) AddAttemptCount(v int) *CheckinRunUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *CheckinRunUpdateOne) SetStartedAt(v time.Time) *CheckinRunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *CheckinRunUpdateOne) SetNillableStartedAt(v *time.Time) *CheckinRunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *CheckinRunUpdateOne) SetFinishedAt(v time.Time) *CheckinRunUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *CheckinRunUpdateOne) SetNillableFinishedAt(v *time.Time) *CheckinRunUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *CheckinRunUpdateOne) ClearFinishedAt() *CheckinRunUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *CheckinRunUpdateOne) SetRequestID(v string) *CheckinRunUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *CheckinRunUpdateOne) SetNillableRequestID(v *string) *CheckinRunUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// Mutation returns the CheckinRunMutation object of the builder.
func (_u *CheckinRunUpdateOne) Mutation() *CheckinRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the CheckinRunUpdate builder.
func (_u *CheckinRunUpdateOne) Where(ps ...predicate.CheckinRun) *CheckinRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CheckinRunUpdateOne) Select(field string, fields ...string) *CheckinRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CheckinRun entity.
func (_u *CheckinRunUpdateOne) Save(ctx context.Context) (*CheckinRun, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckinRunUpdateOne) SaveX(ctx context.Context) *CheckinRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CheckinRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckinRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckinRunUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := checkinrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CheckinRun.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := checkinrun.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "CheckinRun.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AttemptCount(); ok {
		if err := checkinrun.AttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "attempt_count", err: fmt.Errorf(`ent: validator failed for field "CheckinRun.attempt_count": %w`, err)}
		}
	}
	if _u.mutation.SiteCleared() && len(_u.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CheckinRun.site"`)
	}
	return nil
}

func (_u *CheckinRunUpdateOne) sqlSave(ctx context.Context) (_node *CheckinRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkinrun.Table, checkinrun.Columns, sqlgraph.NewFieldSpec(checkinrun.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CheckinRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkinrun.FieldID)
		for _, f := range fields {
			if !checkinrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checkinrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(checkinrun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RewardValue(); ok {
		_spec.SetField(checkinrun.FieldRewardValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRewardValue(); ok {
		_spec.AddField(checkinrun.FieldRewardValue, field.TypeInt64, value)
	}
	if _u.mutation.RewardValueCleared() {
		_spec.ClearField(checkinrun.FieldRewardValue, field.TypeInt64)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(checkinrun.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(checkinrun.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(checkinrun.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(checkinrun.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(checkinrun.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(checkinrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(checkinrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(checkinrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(checkinrun.FieldRequestID, field.TypeString, value)
	}
	_node = &CheckinRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkinrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
