// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/elykia/apihub/server/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/elykia/apihub/server/ent/announcement"
	"github.com/elykia/apihub/server/ent/announcementsyncrun"
	"github.com/elykia/apihub/server/ent/checkinrun"
	"github.com/elykia/apihub/server/ent/site"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Announcement is the client for interacting with the Announcement builders.
	Announcement *AnnouncementClient
	// AnnouncementSyncRun is the client for interacting with the AnnouncementSyncRun builders.
	AnnouncementSyncRun *AnnouncementSyncRunClient
	// CheckinRun is the client for interacting with the CheckinRun builders.
	CheckinRun *CheckinRunClient
	// Site is the client for interacting with the Site builders.
	Site *SiteClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Announcement = NewAnnouncementClient(c.config)
	c.AnnouncementSyncRun = NewAnnouncementSyncRunClient(c.config)
	c.CheckinRun = NewCheckinRunClient(c.config)
	c.Site = NewSiteClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		Announcement:        NewAnnouncementClient(cfg),
		AnnouncementSyncRun: NewAnnouncementSyncRunClient(cfg),
		CheckinRun:          NewCheckinRunClient(cfg),
		Site:                NewSiteClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		Announcement:        NewAnnouncementClient(cfg),
		AnnouncementSyncRun: NewAnnouncementSyncRunClient(cfg),
		CheckinRun:          NewCheckinRunClient(cfg),
		Site:                NewSiteClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Announcement.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Announcement.Use(hooks...)
	c.AnnouncementSyncRun.Use(hooks...)
	c.CheckinRun.Use(hooks...)
	c.Site.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Announcement.Intercept(interceptors...)
	c.AnnouncementSyncRun.Intercept(interceptors...)
	c.CheckinRun.Intercept(interceptors...)
	c.Site.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AnnouncementMutation:
		return c.Announcement.mutate(ctx, m)
	case *AnnouncementSyncRunMutation:
		return c.AnnouncementSyncRun.mutate(ctx, m)
	case *CheckinRunMutation:
		return c.CheckinRun.mutate(ctx, m)
	case *SiteMutation:
		return c.Site.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AnnouncementClient is a client for the Announcement schema.
type AnnouncementClient struct {
	config
}

// NewAnnouncementClient returns a client for the Announcement from the given config.
func NewAnnouncementClient(c config) *AnnouncementClient {
	return &AnnouncementClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `announcement.Hooks(f(g(h())))`.
func (c *AnnouncementClient) Use(hooks ...Hook) {
	c.hooks.Announcement = append(c.hooks.Announcement, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `announcement.Intercept(f(g(h())))`.
func (c *AnnouncementClient) Intercept(interceptors ...Interceptor) {
	c.inters.Announcement = append(c.inters.Announcement, interceptors...)
}

// Create returns a builder for creating a Announcement entity.
func (c *AnnouncementClient) Create() *AnnouncementCreate {
	mutation := newAnnouncementMutation(c.config, OpCreate)
	return &AnnouncementCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Announcement entities.
func (c *AnnouncementClient) CreateBulk(builders ...*AnnouncementCreate) *AnnouncementCreateBulk {
	return &AnnouncementCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AnnouncementClient) MapCreateBulk(slice any, setFunc func(*AnnouncementCreate, int)) *AnnouncementCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AnnouncementCreateBulk{err: fmt.Errorf("calling to AnnouncementClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AnnouncementCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AnnouncementCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Announcement.
func (c *AnnouncementClient) Update() *AnnouncementUpdate {
	mutation := newAnnouncementMutation(c.config, OpUpdate)
	return &AnnouncementUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AnnouncementClient) UpdateOne(_m *Announcement) *AnnouncementUpdateOne {
	mutation := newAnnouncementMutation(c.config, OpUpdateOne, withAnnouncement(_m))
	return &AnnouncementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AnnouncementClient) UpdateOneID(id string) *AnnouncementUpdateOne {
	mutation := newAnnouncementMutation(c.config, OpUpdateOne, withAnnouncementID(id))
	return &AnnouncementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Announcement.
func (c *AnnouncementClient) Delete() *AnnouncementDelete {
	mutation := newAnnouncementMutation(c.config, OpDelete)
	return &AnnouncementDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AnnouncementClient) DeleteOne(_m *Announcement) *AnnouncementDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AnnouncementClient) DeleteOneID(id string) *AnnouncementDeleteOne {
	builder := c.Delete().Where(announcement.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AnnouncementDeleteOne{builder}
}

// Query returns a query builder for Announcement.
func (c *AnnouncementClient) Query() *AnnouncementQuery {
	return &AnnouncementQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAnnouncement},
		inters: c.Interceptors(),
	}
}

// Get returns a Announcement entity by its id.
func (c *AnnouncementClient) Get(ctx context.Context, id string) (*Announcement, error) {
	return c.Query().Where(announcement.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AnnouncementClient) GetX(ctx context.Context, id string) *Announcement {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySite queries the site edge of a Announcement.
func (c *AnnouncementClient) QuerySite(_m *Announcement) *SiteQuery {
	query := (&SiteClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(announcement.Table, announcement.FieldID, id),
			sqlgraph.To(site.Table, site.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, announcement.SiteTable, announcement.SiteColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AnnouncementClient) Hooks() []Hook {
	return c.hooks.Announcement
}

// Interceptors returns the client interceptors.
func (c *AnnouncementClient) Interceptors() []Interceptor {
	return c.inters.Announcement
}

func (c *AnnouncementClient) mutate(ctx context.Context, m *AnnouncementMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AnnouncementCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AnnouncementUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AnnouncementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AnnouncementDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Announcement mutation op: %q", m.Op())
	}
}

// AnnouncementSyncRunClient is a client for the AnnouncementSyncRun schema.
type AnnouncementSyncRunClient struct {
	config
}

// NewAnnouncementSyncRunClient returns a client for the AnnouncementSyncRun from the given config.
func NewAnnouncementSyncRunClient(c config) *AnnouncementSyncRunClient {
	return &AnnouncementSyncRunClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `announcementsyncrun.Hooks(f(g(h())))`.
func (c *AnnouncementSyncRunClient) Use(hooks ...Hook) {
	c.hooks.AnnouncementSyncRun = append(c.hooks.AnnouncementSyncRun, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `announcementsyncrun.Intercept(f(g(h())))`.
func (c *AnnouncementSyncRunClient) Intercept(interceptors ...Interceptor) {
	c.inters.AnnouncementSyncRun = append(c.inters.AnnouncementSyncRun, interceptors...)
}

// Create returns a builder for creating a AnnouncementSyncRun entity.
func (c *AnnouncementSyncRunClient) Create() *AnnouncementSyncRunCreate {
	mutation := newAnnouncementSyncRunMutation(c.config, OpCreate)
	return &AnnouncementSyncRunCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AnnouncementSyncRun entities.
func (c *AnnouncementSyncRunClient) CreateBulk(builders ...*AnnouncementSyncRunCreate) *AnnouncementSyncRunCreateBulk {
	return &AnnouncementSyncRunCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AnnouncementSyncRunClient) MapCreateBulk(slice any, setFunc func(*AnnouncementSyncRunCreate, int)) *AnnouncementSyncRunCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AnnouncementSyncRunCreateBulk{err: fmt.Errorf("calling to AnnouncementSyncRunClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AnnouncementSyncRunCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AnnouncementSyncRunCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AnnouncementSyncRun.
func (c *AnnouncementSyncRunClient) Update() *AnnouncementSyncRunUpdate {
	mutation := newAnnouncementSyncRunMutation(c.config, OpUpdate)
	return &AnnouncementSyncRunUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AnnouncementSyncRunClient) UpdateOne(_m *AnnouncementSyncRun) *AnnouncementSyncRunUpdateOne {
	mutation := newAnnouncementSyncRunMutation(c.config, OpUpdateOne, withAnnouncementSyncRun(_m))
	return &AnnouncementSyncRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AnnouncementSyncRunClient) UpdateOneID(id string) *AnnouncementSyncRunUpdateOne {
	mutation := newAnnouncementSyncRunMutation(c.config, OpUpdateOne, withAnnouncementSyncRunID(id))
	return &AnnouncementSyncRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AnnouncementSyncRun.
func (c *AnnouncementSyncRunClient) Delete() *AnnouncementSyncRunDelete {
	mutation := newAnnouncementSyncRunMutation(c.config, OpDelete)
	return &AnnouncementSyncRunDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AnnouncementSyncRunClient) DeleteOne(_m *AnnouncementSyncRun) *AnnouncementSyncRunDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AnnouncementSyncRunClient) DeleteOneID(id string) *AnnouncementSyncRunDeleteOne {
	builder := c.Delete().Where(announcementsyncrun.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AnnouncementSyncRunDeleteOne{builder}
}

// Query returns a query builder for AnnouncementSyncRun.
func (c *AnnouncementSyncRunClient) Query() *AnnouncementSyncRunQuery {
	return &AnnouncementSyncRunQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAnnouncementSyncRun},
		inters: c.Interceptors(),
	}
}

// Get returns a AnnouncementSyncRun entity by its id.
func (c *AnnouncementSyncRunClient) Get(ctx context.Context, id string) (*AnnouncementSyncRun, error) {
	return c.Query().Where(announcementsyncrun.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AnnouncementSyncRunClient) GetX(ctx context.Context, id string) *AnnouncementSyncRun {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySite queries the site edge of a AnnouncementSyncRun.
func (c *AnnouncementSyncRunClient) QuerySite(_m *AnnouncementSyncRun) *SiteQuery {
	query := (&SiteClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(announcementsyncrun.Table, announcementsyncrun.FieldID, id),
			sqlgraph.To(site.Table, site.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, announcementsyncrun.SiteTable, announcementsyncrun.SiteColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AnnouncementSyncRunClient) Hooks() []Hook {
	return c.hooks.AnnouncementSyncRun
}

// Interceptors returns the client interceptors.
func (c *AnnouncementSyncRunClient) Interceptors() []Interceptor {
	return c.inters.AnnouncementSyncRun
}

func (c *AnnouncementSyncRunClient) mutate(ctx context.Context, m *AnnouncementSyncRunMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AnnouncementSyncRunCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AnnouncementSyncRunUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AnnouncementSyncRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AnnouncementSyncRunDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AnnouncementSyncRun mutation op: %q", m.Op())
	}
}

// CheckinRunClient is a client for the CheckinRun schema.
type CheckinRunClient struct {
	config
}

// NewCheckinRunClient returns a client for the CheckinRun from the given config.
func NewCheckinRunClient(c config) *CheckinRunClient {
	return &CheckinRunClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `checkinrun.Hooks(f(g(h())))`.
func (c *CheckinRunClient) Use(hooks ...Hook) {
	c.hooks.CheckinRun = append(c.hooks.CheckinRun, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `checkinrun.Intercept(f(g(h())))`.
func (c *CheckinRunClient) Intercept(interceptors ...Interceptor) {
	c.inters.CheckinRun = append(c.inters.CheckinRun, interceptors...)
}

// Create returns a builder for creating a CheckinRun entity.
func (c *CheckinRunClient) Create() *CheckinRunCreate {
	mutation := newCheckinRunMutation(c.config, OpCreate)
	return &CheckinRunCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CheckinRun entities.
func (c *CheckinRunClient) CreateBulk(builders ...*CheckinRunCreate) *CheckinRunCreateBulk {
	return &CheckinRunCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CheckinRunClient) MapCreateBulk(slice any, setFunc func(*CheckinRunCreate, int)) *CheckinRunCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CheckinRunCreateBulk{err: fmt.Errorf("calling to CheckinRunClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CheckinRunCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CheckinRunCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CheckinRun.
func (c *CheckinRunClient) Update() *CheckinRunUpdate {
	mutation := newCheckinRunMutation(c.config, OpUpdate)
	return &CheckinRunUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CheckinRunClient) UpdateOne(_m *CheckinRun) *CheckinRunUpdateOne {
	mutation := newCheckinRunMutation(c.config, OpUpdateOne, withCheckinRun(_m))
	return &CheckinRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CheckinRunClient) UpdateOneID(id string) *CheckinRunUpdateOne {
	mutation := newCheckinRunMutation(c.config, OpUpdateOne, withCheckinRunID(id))
	return &CheckinRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CheckinRun.
func (c *CheckinRunClient) Delete() *CheckinRunDelete {
	mutation := newCheckinRunMutation(c.config, OpDelete)
	return &CheckinRunDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CheckinRunClient) DeleteOne(_m *CheckinRun) *CheckinRunDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CheckinRunClient) DeleteOneID(id string) *CheckinRunDeleteOne {
	builder := c.Delete().Where(checkinrun.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CheckinRunDeleteOne{builder}
}

// Query returns a query builder for CheckinRun.
func (c *CheckinRunClient) Query() *CheckinRunQuery {
	return &CheckinRunQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCheckinRun},
		inters: c.Interceptors(),
	}
}

// Get returns a CheckinRun entity by its id.
func (c *CheckinRunClient) Get(ctx context.Context, id string) (*CheckinRun, error) {
	return c.Query().Where(checkinrun.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CheckinRunClient) GetX(ctx context.Context, id string) *CheckinRun {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySite queries the site edge of a CheckinRun.
func (c *CheckinRunClient) QuerySite(_m *CheckinRun) *SiteQuery {
	query := (&SiteClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(checkinrun.Table, checkinrun.FieldID, id),
			sqlgraph.To(site.Table, site.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, checkinrun.SiteTable, checkinrun.SiteColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CheckinRunClient) Hooks() []Hook {
	return c.hooks.CheckinRun
}

// Interceptors returns the client interceptors.
func (c *CheckinRunClient) Interceptors() []Interceptor {
	return c.inters.CheckinRun
}

func (c *CheckinRunClient) mutate(ctx context.Context, m *CheckinRunMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CheckinRunCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CheckinRunUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CheckinRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CheckinRunDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CheckinRun mutation op: %q", m.Op())
	}
}

// SiteClient is a client for the Site schema.
type SiteClient struct {
	config
}

// NewSiteClient returns a client for the Site from the given config.
func NewSiteClient(c config) *SiteClient {
	return &SiteClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `site.Hooks(f(g(h())))`.
func (c *SiteClient) Use(hooks ...Hook) {
	c.hooks.Site = append(c.hooks.Site, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `site.Intercept(f(g(h())))`.
func (c *SiteClient) Intercept(interceptors ...Interceptor) {
	c.inters.Site = append(c.inters.Site, interceptors...)
}

// Create returns a builder for creating a Site entity.
func (c *SiteClient) Create() *SiteCreate {
	mutation := newSiteMutation(c.config, OpCreate)
	return &SiteCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Site entities.
func (c *SiteClient) CreateBulk(builders ...*SiteCreate) *SiteCreateBulk {
	return &SiteCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SiteClient) MapCreateBulk(slice any, setFunc func(*SiteCreate, int)) *SiteCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SiteCreateBulk{err: fmt.Errorf("calling to SiteClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SiteCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SiteCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Site.
func (c *SiteClient) Update() *SiteUpdate {
	mutation := newSiteMutation(c.config, OpUpdate)
	return &SiteUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SiteClient) UpdateOne(_m *Site) *SiteUpdateOne {
	mutation := newSiteMutation(c.config, OpUpdateOne, withSite(_m))
	return &SiteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SiteClient) UpdateOneID(id string) *SiteUpdateOne {
	mutation := newSiteMutation(c.config, OpUpdateOne, withSiteID(id))
	return &SiteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Site.
func (c *SiteClient) Delete() *SiteDelete {
	mutation := newSiteMutation(c.config, OpDelete)
	return &SiteDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SiteClient) DeleteOne(_m *Site) *SiteDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SiteClient) DeleteOneID(id string) *SiteDeleteOne {
	builder := c.Delete().Where(site.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SiteDeleteOne{builder}
}

// Query returns a query builder for Site.
func (c *SiteClient) Query() *SiteQuery {
	return &SiteQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSite},
		inters: c.Interceptors(),
	}
}

// Get returns a Site entity by its id.
func (c *SiteClient) Get(ctx context.Context, id string) (*Site, error) {
	return c.Query().Where(site.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SiteClient) GetX(ctx context.Context, id string) *Site {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCheckinRuns queries the checkin_runs edge of a Site.
func (c *SiteClient) QueryCheckinRuns(_m *Site) *CheckinRunQuery {
	query := (&CheckinRunClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(site.Table, site.FieldID, id),
			sqlgraph.To(checkinrun.Table, checkinrun.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, site.CheckinRunsTable, site.CheckinRunsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAnnouncementSyncRuns queries the announcement_sync_runs edge of a Site.
func (c *SiteClient) QueryAnnouncementSyncRuns(_m *Site) *AnnouncementSyncRunQuery {
	query := (&AnnouncementSyncRunClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(site.Table, site.FieldID, id),
			sqlgraph.To(announcementsyncrun.Table, announcementsyncrun.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, site.AnnouncementSyncRunsTable, site.AnnouncementSyncRunsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAnnouncements queries the announcements edge of a Site.
func (c *SiteClient) QueryAnnouncements(_m *Site) *AnnouncementQuery {
	query := (&AnnouncementClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(site.Table, site.FieldID, id),
			sqlgraph.To(announcement.Table, announcement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, site.AnnouncementsTable, site.AnnouncementsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SiteClient) Hooks() []Hook {
	return c.hooks.Site
}

// Interceptors returns the client interceptors.
func (c *SiteClient) Interceptors() []Interceptor {
	return c.inters.Site
}

func (c *SiteClient) mutate(ctx context.Context, m *SiteMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SiteCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SiteUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SiteUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SiteDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Site mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Announcement, AnnouncementSyncRun, CheckinRun, Site []ent.Hook
	}
	inters struct {
		Announcement, AnnouncementSyncRun, CheckinRun, Site []ent.Interceptor
	}
)
