// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/elykia/apihub/server/ent/announcement"
	"github.com/elykia/apihub/server/ent/announcementsyncrun"
	"github.com/elykia/apihub/server/ent/checkinrun"
	"github.com/elykia/apihub/server/ent/schema"
	"github.com/elykia/apihub/server/ent/site"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	announcementFields := schema.Announcement{}.Fields()
	_ = announcementFields
	// announcementDescKind is the schema descriptor for kind field.
	announcementDescKind := announcementFields[5].Descriptor()
	// announcement.DefaultKind holds the default value on creation for the kind field.
	announcement.DefaultKind = announcementDescKind.Default.(string)
	// announcement.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	announcement.KindValidator = announcementDescKind.Validators[0].(func(string) error)
	announcementsyncrunFields := schema.AnnouncementSyncRun{}.Fields()
	_ = announcementsyncrunFields
	// announcementsyncrunDescAddedCount is the schema descriptor for added_count field.
	announcementsyncrunDescAddedCount := announcementsyncrunFields[3].Descriptor()
	// announcementsyncrun.DefaultAddedCount holds the default value on creation for the added_count field.
	announcementsyncrun.DefaultAddedCount = announcementsyncrunDescAddedCount.Default.(int)
	// announcementsyncrun.AddedCountValidator is a validator for the "added_count" field. It is called by the builders before save.
	announcementsyncrun.AddedCountValidator = announcementsyncrunDescAddedCount.Validators[0].(func(int) error)
	// announcementsyncrunDescMessage is the schema descriptor for message field.
	announcementsyncrunDescMessage := announcementsyncrunFields[4].Descriptor()
	// announcementsyncrun.DefaultMessage holds the default value on creation for the message field.
	announcementsyncrun.DefaultMessage = announcementsyncrunDescMessage.Default.(string)
	checkinrunFields := schema.CheckinRun{}.Fields()
	_ = checkinrunFields
	// checkinrunDescMessage is the schema descriptor for message field.
	checkinrunDescMessage := checkinrunFields[5].Descriptor()
	// checkinrun.DefaultMessage holds the default value on creation for the message field.
	checkinrun.DefaultMessage = checkinrunDescMessage.Default.(string)
	// checkinrunDescErrorCode is the schema descriptor for error_code field.
	checkinrunDescErrorCode := checkinrunFields[6].Descriptor()
	// checkinrun.ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	checkinrun.ErrorCodeValidator = checkinrunDescErrorCode.Validators[0].(func(string) error)
	// checkinrunDescAttemptCount is the schema descriptor for attempt_count field.
	checkinrunDescAttemptCount := checkinrunFields[7].Descriptor()
	// checkinrun.DefaultAttemptCount holds the default value on creation for the attempt_count field.
	checkinrun.DefaultAttemptCount = checkinrunDescAttemptCount.Default.(int)
	// checkinrun.AttemptCountValidator is a validator for the "attempt_count" field. It is called by the builders before save.
	checkinrun.AttemptCountValidator = checkinrunDescAttemptCount.Validators[0].(func(int) error)
	siteFields := schema.Site{}.Fields()
	_ = siteFields
	// siteDescName is the schema descriptor for name field.
	siteDescName := siteFields[1].Descriptor()
	// site.NameValidator is a validator for the "name" field. It is called by the builders before save.
	site.NameValidator = siteDescName.Validators[0].(func(string) error)
	// siteDescUserID is the schema descriptor for user_id field.
	siteDescUserID := siteFields[4].Descriptor()
	// site.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	site.UserIDValidator = siteDescUserID.Validators[0].(func(string) error)
	// siteDescEnabled is the schema descriptor for enabled field.
	siteDescEnabled := siteFields[6].Descriptor()
	// site.DefaultEnabled holds the default value on creation for the enabled field.
	site.DefaultEnabled = siteDescEnabled.Default.(bool)
	// siteDescCheckinEnabled is the schema descriptor for checkin_enabled field.
	siteDescCheckinEnabled := siteFields[7].Descriptor()
	// site.DefaultCheckinEnabled holds the default value on creation for the checkin_enabled field.
	site.DefaultCheckinEnabled = siteDescCheckinEnabled.Default.(bool)
	// siteDescAnnouncementEnabled is the schema descriptor for announcement_enabled field.
	siteDescAnnouncementEnabled := siteFields[8].Descriptor()
	// site.DefaultAnnouncementEnabled holds the default value on creation for the announcement_enabled field.
	site.DefaultAnnouncementEnabled = siteDescAnnouncementEnabled.Default.(bool)
	// siteDescCheckinCron is the schema descriptor for checkin_cron field.
	siteDescCheckinCron := siteFields[9].Descriptor()
	// site.CheckinCronValidator is a validator for the "checkin_cron" field. It is called by the builders before save.
	site.CheckinCronValidator = siteDescCheckinCron.Validators[0].(func(string) error)
	// siteDescAnnouncementCron is the schema descriptor for announcement_cron field.
	siteDescAnnouncementCron := siteFields[10].Descriptor()
	// site.AnnouncementCronValidator is a validator for the "announcement_cron" field. It is called by the builders before save.
	site.AnnouncementCronValidator = siteDescAnnouncementCron.Validators[0].(func(string) error)
	// siteDescTimezone is the schema descriptor for timezone field.
	siteDescTimezone := siteFields[11].Descriptor()
	// site.TimezoneValidator is a validator for the "timezone" field. It is called by the builders before save.
	site.TimezoneValidator = siteDescTimezone.Validators[0].(func(string) error)
	// siteDescConsecutiveFailures is the schema descriptor for consecutive_failures field.
	siteDescConsecutiveFailures := siteFields[12].Descriptor()
	// site.DefaultConsecutiveFailures holds the default value on creation for the consecutive_failures field.
	site.DefaultConsecutiveFailures = siteDescConsecutiveFailures.Default.(int)
	// site.ConsecutiveFailuresValidator is a validator for the "consecutive_failures" field. It is called by the builders before save.
	site.ConsecutiveFailuresValidator = siteDescConsecutiveFailures.Validators[0].(func(int) error)
}
