// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/elykia/apihub/server/ent/site"
)

// Site is the model entity for the Site schema.
type Site struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// BaseURL holds the value of the "base_url" field.
	BaseURL string `json:"base_url,omitempty"`
	// Adapter holds the value of the "adapter" field.
	Adapter site.Adapter `json:"adapter,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// AccessTokenCiphertext holds the value of the "access_token_ciphertext" field.
	AccessTokenCiphertext string `json:"access_token_ciphertext,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CheckinEnabled holds the value of the "checkin_enabled" field.
	CheckinEnabled bool `json:"checkin_enabled,omitempty"`
	// AnnouncementEnabled holds the value of the "announcement_enabled" field.
	AnnouncementEnabled bool `json:"announcement_enabled,omitempty"`
	// CheckinCron holds the value of the "checkin_cron" field.
	CheckinCron string `json:"checkin_cron,omitempty"`
	// AnnouncementCron holds the value of the "announcement_cron" field.
	AnnouncementCron string `json:"announcement_cron,omitempty"`
	// Timezone holds the value of the "timezone" field.
	Timezone string `json:"timezone,omitempty"`
	// ConsecutiveFailures holds the value of the "consecutive_failures" field.
	ConsecutiveFailures int `json:"consecutive_failures,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SiteQuery when eager-loading is set.
	Edges        SiteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SiteEdges holds the relations/edges for other nodes in the graph.
type SiteEdges struct {
	// CheckinRuns holds the value of the checkin_runs edge.
	CheckinRuns []*CheckinRun `json:"checkin_runs,omitempty"`
	// AnnouncementSyncRuns holds the value of the announcement_sync_runs edge.
	AnnouncementSyncRuns []*AnnouncementSyncRun `json:"announcement_sync_runs,omitempty"`
	// Announcements holds the value of the announcements edge.
	Announcements []*Announcement `json:"announcements,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// CheckinRunsOrErr returns the CheckinRuns value or an error if the edge
// was not loaded in eager-loading.
func (e SiteEdges) CheckinRunsOrErr() ([]*CheckinRun, error) {
	if e.loadedTypes[0] {
		return e.CheckinRuns, nil
	}
	return nil, &NotLoadedError{edge: "checkin_runs"}
}

// AnnouncementSyncRunsOrErr returns the AnnouncementSyncRuns value or an error if the edge
// was not loaded in eager-loading.
func (e SiteEdges) AnnouncementSyncRunsOrErr() ([]*AnnouncementSyncRun, error) {
	if e.loadedTypes[1] {
		return e.AnnouncementSyncRuns, nil
	}
	return nil, &NotLoadedError{edge: "announcement_sync_runs"}
}

// AnnouncementsOrErr returns the Announcements value or an error if the edge
// was not loaded in eager-loading.
func (e SiteEdges) AnnouncementsOrErr() ([]*Announcement, error) {
	if e.loadedTypes[2] {
		return e.Announcements, nil
	}
	return nil, &NotLoadedError{edge: "announcements"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Site) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case site.FieldEnabled, site.FieldCheckinEnabled, site.FieldAnnouncementEnabled:
			values[i] = new(sql.NullBool)
		case site.FieldConsecutiveFailures:
			values[i] = new(sql.NullInt64)
		case site.FieldID, site.FieldName, site.FieldBaseURL, site.FieldAdapter, site.FieldUserID, site.FieldAccessTokenCiphertext, site.FieldCheckinCron, site.FieldAnnouncementCron, site.FieldTimezone:
			values[i] = new(sql.NullString)
		case site.FieldCreatedAt, site.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Site fields.
func (_m *Site) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case site.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case site.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case site.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case site.FieldAdapter:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field adapter", values[i])
			} else if value.Valid {
				_m.Adapter = site.Adapter(value.String)
			}
		case site.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case site.FieldAccessTokenCiphertext:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token_ciphertext", values[i])
			} else if value.Valid {
				_m.AccessTokenCiphertext = value.String
			}
		case site.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case site.FieldCheckinEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field checkin_enabled", values[i])
			} else if value.Valid {
				_m.CheckinEnabled = value.Bool
			}
		case site.FieldAnnouncementEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field announcement_enabled", values[i])
			} else if value.Valid {
				_m.AnnouncementEnabled = value.Bool
			}
		case site.FieldCheckinCron:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checkin_cron", values[i])
			} else if value.Valid {
				_m.CheckinCron = value.String
			}
		case site.FieldAnnouncementCron:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field announcement_cron", values[i])
			} else if value.Valid {
				_m.AnnouncementCron = value.String
			}
		case site.FieldTimezone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field timezone", values[i])
			} else if value.Valid {
				_m.Timezone = value.String
			}
		case site.FieldConsecutiveFailures:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consecutive_failures", values[i])
			} else if value.Valid {
				_m.ConsecutiveFailures = int(value.Int64)
			}
		case site.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case site.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Site.
// This includes values selected through modifiers, order, etc.
func (_m *Site) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCheckinRuns queries the "checkin_runs" edge of the Site entity.
func (_m *Site) QueryCheckinRuns() *CheckinRunQuery {
	return NewSiteClient(_m.config).QueryCheckinRuns(_m)
}

// QueryAnnouncementSyncRuns queries the "announcement_sync_runs" edge of the Site entity.
func (_m *Site) QueryAnnouncementSyncRuns() *AnnouncementSyncRunQuery {
	return NewSiteClient(_m.config).QueryAnnouncementSyncRuns(_m)
}

// QueryAnnouncements queries the "announcements" edge of the Site entity.
func (_m *Site) QueryAnnouncements() *AnnouncementQuery {
	return NewSiteClient(_m.config).QueryAnnouncements(_m)
}

// Update returns a builder for updating this Site.
// Note that you need to call Site.Unwrap() before calling this method if this Site
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Site) Update() *SiteUpdateOne {
	return NewSiteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Site entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Site) Unwrap() *Site {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Site is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Site) String() string {
	var builder strings.Builder
	builder.WriteString("Site(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	builder.WriteString("adapter=")
	builder.WriteString(fmt.Sprintf("%v", _m.Adapter))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("access_token_ciphertext=")
	builder.WriteString(_m.AccessTokenCiphertext)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("checkin_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.CheckinEnabled))
	builder.WriteString(", ")
	builder.WriteString("announcement_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.AnnouncementEnabled))
	builder.WriteString(", ")
	builder.WriteString("checkin_cron=")
	builder.WriteString(_m.CheckinCron)
	builder.WriteString(", ")
	builder.WriteString("announcement_cron=")
	builder.WriteString(_m.AnnouncementCron)
	builder.WriteString(", ")
	builder.WriteString("timezone=")
	builder.WriteString(_m.Timezone)
	builder.WriteString(", ")
	builder.WriteString("consecutive_failures=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsecutiveFailures))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Sites is a parsable slice of Site.
type Sites []*Site
