// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elykia/apihub/server/ent/announcement"
	"github.com/elykia/apihub/server/ent/announcementsyncrun"
	"github.com/elykia/apihub/server/ent/checkinrun"
	"github.com/elykia/apihub/server/ent/site"
)

// SiteCreate is the builder for creating a Site entity.
type SiteCreate struct {
	config
	mutation *SiteMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *SiteCreate) SetName(v string) *SiteCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *SiteCreate) SetBaseURL(v string) *SiteCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetAdapter sets the "adapter" field.
func (_c *SiteCreate) SetAdapter(v site.Adapter) *SiteCreate {
	_c.mutation.SetAdapter(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SiteCreate) SetUserID(v string) *SiteCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAccessTokenCiphertext sets the "access_token_ciphertext" field.
func (_c *SiteCreate) SetAccessTokenCiphertext(v string) *SiteCreate {
	_c.mutation.SetAccessTokenCiphertext(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *SiteCreate) SetEnabled(v bool) *SiteCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *SiteCreate) SetNillableEnabled(v *bool) *SiteCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCheckinEnabled sets the "checkin_enabled" field.
func (_c *SiteCreate) SetCheckinEnabled(v bool) *SiteCreate {
	_c.mutation.SetCheckinEnabled(v)
	return _c
}

// SetNillableCheckinEnabled sets the "checkin_enabled" field if the given value is not nil.
func (_c *SiteCreate) SetNillableCheckinEnabled(v *bool) *SiteCreate {
	if v != nil {
		_c.SetCheckinEnabled(*v)
	}
	return _c
}

// SetAnnouncementEnabled sets the "announcement_enabled" field.
func (_c *SiteCreate) SetAnnouncementEnabled(v bool) *SiteCreate {
	_c.mutation.SetAnnouncementEnabled(v)
	return _c
}

// SetNillableAnnouncementEnabled sets the "announcement_enabled" field if the given value is not nil.
func (_c *SiteCreate) SetNillableAnnouncementEnabled(v *bool) *SiteCreate {
	if v != nil {
		_c.SetAnnouncementEnabled(*v)
	}
	return _c
}

// SetCheckinCron sets the "checkin_cron" field.
func (_c *SiteCreate) SetCheckinCron(v string) *SiteCreate {
	_c.mutation.SetCheckinCron(v)
	return _c
}

// SetAnnouncementCron sets the "announcement_cron" field.
func (_c *SiteCreate) SetAnnouncementCron(v string) *SiteCreate {
	_c.mutation.SetAnnouncementCron(v)
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *SiteCreate) SetTimezone(v string) *SiteCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_c *SiteCreate) SetConsecutiveFailures(v int) *SiteCreate {
	_c.mutation.SetConsecutiveFailures(v)
	return _c
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_c *SiteCreate) SetNillableConsecutiveFailures(v *int) *SiteCreate {
	if v != nil {
		_c.SetConsecutiveFailures(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SiteCreate) SetCreatedAt(v time.Time) *SiteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SiteCreate) SetUpdatedAt(v time.Time) *SiteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SiteCreate) SetID(v string) *SiteCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddCheckinRunIDs adds the "checkin_runs" edge to the CheckinRun entity by IDs.
func (_c *SiteCreate) AddCheckinRunIDs(ids ...string) *SiteCreate {
	_c.mutation.AddCheckinRunIDs(ids...)
	return _c
}

// AddCheckinRuns adds the "checkin_runs" edges to the CheckinRun entity.
func (_c *SiteCreate) AddCheckinRuns(v ...*CheckinRun) *SiteCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCheckinRunIDs(ids...)
}

// AddAnnouncementSyncRunIDs adds the "announcement_sync_runs" edge to the AnnouncementSyncRun entity by IDs.
func (_c *SiteCreate) AddAnnouncementSyncRunIDs(ids ...string) *SiteCreate {
	_c.mutation.AddAnnouncementSyncRunIDs(ids...)
	return _c
}

// AddAnnouncementSyncRuns adds the "announcement_sync_runs" edges to the AnnouncementSyncRun entity.
func (_c *SiteCreate) AddAnnouncementSyncRuns(v ...*AnnouncementSyncRun) *SiteCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAnnouncementSyncRunIDs(ids...)
}

// AddAnnouncementIDs adds the "announcements" edge to the Announcement entity by IDs.
func (_c *SiteCreate) AddAnnouncementIDs(ids ...string) *SiteCreate {
	_c.mutation.AddAnnouncementIDs(ids...)
	return _c
}

// AddAnnouncements adds the "announcements" edges to the Announcement entity.
func (_c *SiteCreate) AddAnnouncements(v ...*Announcement) *SiteCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAnnouncementIDs(ids...)
}

// Mutation returns the SiteMutation object of the builder.
func (_c *SiteCreate) Mutation() *SiteMutation {
	return _c.mutation
}

// Save creates the Site in the database.
func (_c *SiteCreate) Save(ctx context.Context) (*Site, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SiteCreate) SaveX(ctx context.Context) *Site {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SiteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SiteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SiteCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := site.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CheckinEnabled(); !ok {
		v := site.DefaultCheckinEnabled
		_c.mutation.SetCheckinEnabled(v)
	}
	if _, ok := _c.mutation.AnnouncementEnabled(); !ok {
		v := site.DefaultAnnouncementEnabled
		_c.mutation.SetAnnouncementEnabled(v)
	}
	if _, ok := _c.mutation.ConsecutiveFailures(); !ok {
		v := site.DefaultConsecutiveFailures
		_c.mutation.SetConsecutiveFailures(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SiteCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Site.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := site.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Site.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseURL(); !ok {
		return &ValidationError{Name: "base_url", err: errors.New(`ent: missing required field "Site.base_url"`)}
	}
	if _, ok := _c.mutation.Adapter(); !ok {
		return &ValidationError{Name: "adapter", err: errors.New(`ent: missing required field "Site.adapter"`)}
	}
	if v, ok := _c.mutation.Adapter(); ok {
		if err := site.AdapterValidator(v); err != nil {
			return &ValidationError{Name: "adapter", err: fmt.Errorf(`ent: validator failed for field "Site.adapter": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Site.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := site.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Site.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccessTokenCiphertext(); !ok {
		return &ValidationError{Name: "access_token_ciphertext", err: errors.New(`ent: missing required field "Site.access_token_ciphertext"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Site.enabled"`)}
	}
	if _, ok := _c.mutation.CheckinEnabled(); !ok {
		return &ValidationError{Name: "checkin_enabled", err: errors.New(`ent: missing required field "Site.checkin_enabled"`)}
	}
	if _, ok := _c.mutation.AnnouncementEnabled(); !ok {
		return &ValidationError{Name: "announcement_enabled", err: errors.New(`ent: missing required field "Site.announcement_enabled"`)}
	}
	if _, ok := _c.mutation.CheckinCron(); !ok {
		return &ValidationError{Name: "checkin_cron", err: errors.New(`ent: missing required field "Site.checkin_cron"`)}
	}
	if v, ok := _c.mutation.CheckinCron(); ok {
		if err := site.CheckinCronValidator(v); err != nil {
			return &ValidationError{Name: "checkin_cron", err: fmt.Errorf(`ent: validator failed for field "Site.checkin_cron": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AnnouncementCron(); !ok {
		return &ValidationError{Name: "announcement_cron", err: errors.New(`ent: missing required field "Site.announcement_cron"`)}
	}
	if v, ok := _c.mutation.AnnouncementCron(); ok {
		if err := site.AnnouncementCronValidator(v); err != nil {
			return &ValidationError{Name: "announcement_cron", err: fmt.Errorf(`ent: validator failed for field "Site.announcement_cron": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "Site.timezone"`)}
	}
	if v, ok := _c.mutation.Timezone(); ok {
		if err := site.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "Site.timezone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ConsecutiveFailures(); !ok {
		return &ValidationError{Name: "consecutive_failures", err: errors.New(`ent: missing required field "Site.consecutive_failures"`)}
	}
	if v, ok := _c.mutation.ConsecutiveFailures(); ok {
		if err := site.ConsecutiveFailuresValidator(v); err != nil {
			return &ValidationError{Name: "consecutive_failures", err: fmt.Errorf(`ent: validator failed for field "Site.consecutive_failures": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Site.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Site.updated_at"`)}
	}
	return nil
}

func (_c *SiteCreate) sqlSave(ctx context.Context) (*Site, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Site.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SiteCreate) createSpec() (*Site, *sqlgraph.CreateSpec) {
	var (
		_node = &Site{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(site.Table, sqlgraph.NewFieldSpec(site.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(site.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(site.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.Adapter(); ok {
		_spec.SetField(site.FieldAdapter, field.TypeEnum, value)
		_node.Adapter = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(site.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.AccessTokenCiphertext(); ok {
		_spec.SetField(site.FieldAccessTokenCiphertext, field.TypeString, value)
		_node.AccessTokenCiphertext = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(site.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CheckinEnabled(); ok {
		_spec.SetField(site.FieldCheckinEnabled, field.TypeBool, value)
		_node.CheckinEnabled = value
	}
	if value, ok := _c.mutation.AnnouncementEnabled(); ok {
		_spec.SetField(site.FieldAnnouncementEnabled, field.TypeBool, value)
		_node.AnnouncementEnabled = value
	}
	if value, ok := _c.mutation.CheckinCron(); ok {
		_spec.SetField(site.FieldCheckinCron, field.TypeString, value)
		_node.CheckinCron = value
	}
	if value, ok := _c.mutation.AnnouncementCron(); ok {
		_spec.SetField(site.FieldAnnouncementCron, field.TypeString, value)
		_node.AnnouncementCron = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(site.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(site.FieldConsecutiveFailures, field.TypeInt, value)
		_node.ConsecutiveFailures = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(site.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(site.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CheckinRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.CheckinRunsTable,
			Columns: []string{site.CheckinRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkinrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AnnouncementSyncRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.AnnouncementSyncRunsTable,
			Columns: []string{site.AnnouncementSyncRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementsyncrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AnnouncementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.AnnouncementsTable,
			Columns: []string{site.AnnouncementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SiteCreateBulk is the builder for creating many Site entities in bulk.
type SiteCreateBulk struct {
	config
	err      error
	builders []*SiteCreate
}

// Save creates the Site entities in the database.
func (_c *SiteCreateBulk) Save(ctx context.Context) ([]*Site, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Site, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SiteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SiteCreateBulk) SaveX(ctx context.Context) []*Site {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SiteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SiteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
