// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elykia/apihub/server/ent/announcement"
	"github.com/elykia/apihub/server/ent/announcementsyncrun"
	"github.com/elykia/apihub/server/ent/checkinrun"
	"github.com/elykia/apihub/server/ent/predicate"
	"github.com/elykia/apihub/server/ent/site"
)

// SiteUpdate is the builder for updating Site entities.
type SiteUpdate struct {
	config
	hooks    []Hook
	mutation *SiteMutation
}

// Where appends a list predicates to the SiteUpdate builder.
func (_u *SiteUpdate) Where(ps ...predicate.Site) *SiteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SiteUpdate) SetName(v string) *SiteUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableName(v *string) *SiteUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *SiteUpdate) SetBaseURL(v string) *SiteUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableBaseURL(v *string) *SiteUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetAdapter sets the "adapter" field.
func (_u *SiteUpdate) SetAdapter(v site.Adapter) *SiteUpdate {
	_u.mutation.SetAdapter(v)
	return _u
}

// SetNillableAdapter sets the "adapter" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableAdapter(v *site.Adapter) *SiteUpdate {
	if v != nil {
		_u.SetAdapter(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SiteUpdate) SetUserID(v string) *SiteUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableUserID(v *string) *SiteUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAccessTokenCiphertext sets the "access_token_ciphertext" field.
func (_u *SiteUpdate) SetAccessTokenCiphertext(v string) *SiteUpdate {
	_u.mutation.SetAccessTokenCiphertext(v)
	return _u
}

// SetNillableAccessTokenCiphertext sets the "access_token_ciphertext" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableAccessTokenCiphertext(v *string) *SiteUpdate {
	if v != nil {
		_u.SetAccessTokenCiphertext(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SiteUpdate) SetEnabled(v bool) *SiteUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableEnabled(v *bool) *SiteUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCheckinEnabled sets the "checkin_enabled" field.
func (_u *SiteUpdate) SetCheckinEnabled(v bool) *SiteUpdate {
	_u.mutation.SetCheckinEnabled(v)
	return _u
}

// SetNillableCheckinEnabled sets the "checkin_enabled" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableCheckinEnabled(v *bool) *SiteUpdate {
	if v != nil {
		_u.SetCheckinEnabled(*v)
	}
	return _u
}

// SetAnnouncementEnabled sets the "announcement_enabled" field.
func (_u *SiteUpdate) SetAnnouncementEnabled(v bool) *SiteUpdate {
	_u.mutation.SetAnnouncementEnabled(v)
	return _u
}

// SetNillableAnnouncementEnabled sets the "announcement_enabled" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableAnnouncementEnabled(v *bool) *SiteUpdate {
	if v != nil {
		_u.SetAnnouncementEnabled(*v)
	}
	return _u
}

// SetCheckinCron sets the "checkin_cron" field.
func (_u *SiteUpdate) SetCheckinCron(v string) *SiteUpdate {
	_u.mutation.SetCheckinCron(v)
	return _u
}

// SetNillableCheckinCron sets the "checkin_cron" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableCheckinCron(v *string) *SiteUpdate {
	if v != nil {
		_u.SetCheckinCron(*v)
	}
	return _u
}

// SetAnnouncementCron sets the "announcement_cron" field.
func (_u *SiteUpdate) SetAnnouncementCron(v string) *SiteUpdate {
	_u.mutation.SetAnnouncementCron(v)
	return _u
}

// SetNillableAnnouncementCron sets the "announcement_cron" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableAnnouncementCron(v *string) *SiteUpdate {
	if v != nil {
		_u.SetAnnouncementCron(*v)
	}
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *SiteUpdate) SetTimezone(v string) *SiteUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableTimezone(v *string) *SiteUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *SiteUpdate) SetConsecutiveFailures(v int) *SiteUpdate {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableConsecutiveFailures(v *int) *SiteUpdate {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *SiteUpdate) AddConsecutiveFailures(v int) *SiteUpdate {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SiteUpdate) SetUpdatedAt(v time.Time) *SiteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableUpdatedAt(v *time.Time) *SiteUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddCheckinRunIDs adds the "checkin_runs" edge to the CheckinRun entity by IDs.
func (_u *SiteUpdate) AddCheckinRunIDs(ids ...string) *SiteUpdate {
	_u.mutation.AddCheckinRunIDs(ids...)
	return _u
}

// AddCheckinRuns adds the "checkin_runs" edges to the CheckinRun entity.
func (_u *SiteUpdate) AddCheckinRuns(v ...*CheckinRun) *SiteUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCheckinRunIDs(ids...)
}

// AddAnnouncementSyncRunIDs adds the "announcement_sync_runs" edge to the AnnouncementSyncRun entity by IDs.
func (_u *SiteUpdate) AddAnnouncementSyncRunIDs(ids ...string) *SiteUpdate {
	_u.mutation.AddAnnouncementSyncRunIDs(ids...)
	return _u
}

// AddAnnouncementSyncRuns adds the "announcement_sync_runs" edges to the AnnouncementSyncRun entity.
func (_u *SiteUpdate) AddAnnouncementSyncRuns(v ...*AnnouncementSyncRun) *SiteUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnnouncementSyncRunIDs(ids...)
}

// AddAnnouncementIDs adds the "announcements" edge to the Announcement entity by IDs.
func (_u *SiteUpdate) AddAnnouncementIDs(ids ...string) *SiteUpdate {
	_u.mutation.AddAnnouncementIDs(ids...)
	return _u
}

// AddAnnouncements adds the "announcements" edges to the Announcement entity.
func (_u *SiteUpdate) AddAnnouncements(v ...*Announcement) *SiteUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnnouncementIDs(ids...)
}

// Mutation returns the SiteMutation object of the builder.
func (_u *SiteUpdate) Mutation() *SiteMutation {
	return _u.mutation
}

// ClearCheckinRuns clears all "checkin_runs" edges to the CheckinRun entity.
func (_u *SiteUpdate) ClearCheckinRuns() *SiteUpdate {
	_u.mutation.ClearCheckinRuns()
	return _u
}

// RemoveCheckinRunIDs removes the "checkin_runs" edge to CheckinRun entities by IDs.
func (_u *SiteUpdate) RemoveCheckinRunIDs(ids ...string) *SiteUpdate {
	_u.mutation.RemoveCheckinRunIDs(ids...)
	return _u
}

// RemoveCheckinRuns removes "checkin_runs" edges to CheckinRun entities.
func (_u *SiteUpdate) RemoveCheckinRuns(v ...*CheckinRun) *SiteUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCheckinRunIDs(ids...)
}

// ClearAnnouncementSyncRuns clears all "announcement_sync_runs" edges to the AnnouncementSyncRun entity.
func (_u *SiteUpdate) ClearAnnouncementSyncRuns() *SiteUpdate {
	_u.mutation.ClearAnnouncementSyncRuns()
	return _u
}

// RemoveAnnouncementSyncRunIDs removes the "announcement_sync_runs" edge to AnnouncementSyncRun entities by IDs.
func (_u *SiteUpdate) RemoveAnnouncementSyncRunIDs(ids ...string) *SiteUpdate {
	_u.mutation.RemoveAnnouncementSyncRunIDs(ids...)
	return _u
}

// RemoveAnnouncementSyncRuns removes "announcement_sync_runs" edges to AnnouncementSyncRun entities.
func (_u *SiteUpdate) RemoveAnnouncementSyncRuns(v ...*AnnouncementSyncRun) *SiteUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnnouncementSyncRunIDs(ids...)
}

// ClearAnnouncements clears all "announcements" edges to the Announcement entity.
func (_u *SiteUpdate) ClearAnnouncements() *SiteUpdate {
	_u.mutation.ClearAnnouncements()
	return _u
}

// RemoveAnnouncementIDs removes the "announcements" edge to Announcement entities by IDs.
func (_u *SiteUpdate) RemoveAnnouncementIDs(ids ...string) *SiteUpdate {
	_u.mutation.RemoveAnnouncementIDs(ids...)
	return _u
}

// RemoveAnnouncements removes "announcements" edges to Announcement entities.
func (_u *SiteUpdate) RemoveAnnouncements(v ...*Announcement) *SiteUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnnouncementIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SiteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SiteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SiteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SiteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SiteUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := site.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Site.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Adapter(); ok {
		if err := site.AdapterValidator(v); err != nil {
			return &ValidationError{Name: "adapter", err: fmt.Errorf(`ent: validator failed for field "Site.adapter": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := site.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Site.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CheckinCron(); ok {
		if err := site.CheckinCronValidator(v); err != nil {
			return &ValidationError{Name: "checkin_cron", err: fmt.Errorf(`ent: validator failed for field "Site.checkin_cron": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AnnouncementCron(); ok {
		if err := site.AnnouncementCronValidator(v); err != nil {
			return &ValidationError{Name: "announcement_cron", err: fmt.Errorf(`ent: validator failed for field "Site.announcement_cron": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timezone(); ok {
		if err := site.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "Site.timezone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConsecutiveFailures(); ok {
		if err := site.ConsecutiveFailuresValidator(v); err != nil {
			return &ValidationError{Name: "consecutive_failures", err: fmt.Errorf(`ent: validator failed for field "Site.consecutive_failures": %w`, err)}
		}
	}
	return nil
}

func (_u *SiteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(site.Table, site.Columns, sqlgraph.NewFieldSpec(site.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(site.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(site.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Adapter(); ok {
		_spec.SetField(site.FieldAdapter, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(site.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessTokenCiphertext(); ok {
		_spec.SetField(site.FieldAccessTokenCiphertext, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(site.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CheckinEnabled(); ok {
		_spec.SetField(site.FieldCheckinEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AnnouncementEnabled(); ok {
		_spec.SetField(site.FieldAnnouncementEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CheckinCron(); ok {
		_spec.SetField(site.FieldCheckinCron, field.TypeString, value)
	}
	if value, ok := _u.mutation.AnnouncementCron(); ok {
		_spec.SetField(site.FieldAnnouncementCron, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(site.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(site.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(site.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(site.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CheckinRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.CheckinRunsTable,
			Columns: []string{site.CheckinRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkinrun.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCheckinRunsIDs(); len(nodes) > 0 && !_u.mutation.CheckinRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.CheckinRunsTable,
			Columns: []string{site.CheckinRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkinrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CheckinRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.CheckinRunsTable,
			Columns: []string{site.CheckinRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkinrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnnouncementSyncRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.AnnouncementSyncRunsTable,
			Columns: []string{site.AnnouncementSyncRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementsyncrun.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnnouncementSyncRunsIDs(); len(nodes) > 0 && !_u.mutation.AnnouncementSyncRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.AnnouncementSyncRunsTable,
			Columns: []string{site.AnnouncementSyncRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementsyncrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnnouncementSyncRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.AnnouncementSyncRunsTable,
			Columns: []string{site.AnnouncementSyncRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementsyncrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnnouncementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.AnnouncementsTable,
			Columns: []string{site.AnnouncementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnnouncementsIDs(); len(nodes) > 0 && !_u.mutation.AnnouncementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.AnnouncementsTable,
			Columns: []string{site.AnnouncementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnnouncementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.AnnouncementsTable,
			Columns: []string{site.AnnouncementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{site.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SiteUpdateOne is the builder for updating a single Site entity.
type SiteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SiteMutation
}

// SetName sets the "name" field.
func (_u *SiteUpdateOne) SetName(v string) *SiteUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableName(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *SiteUpdateOne) SetBaseURL(v string) *SiteUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableBaseURL(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetAdapter sets the "adapter" field.
func (_u *SiteUpdateOne) SetAdapter(v site.Adapter) *SiteUpdateOne {
	_u.mutation.SetAdapter(v)
	return _u
}

// SetNillableAdapter sets the "adapter" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableAdapter(v *site.Adapter) *SiteUpdateOne {
	if v != nil {
		_u.SetAdapter(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SiteUpdateOne) SetUserID(v string) *SiteUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableUserID(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAccessTokenCiphertext sets the "access_token_ciphertext" field.
func (_u *SiteUpdateOne) SetAccessTokenCiphertext(v string) *SiteUpdateOne {
	_u.mutation.SetAccessTokenCiphertext(v)
	return _u
}

// SetNillableAccessTokenCiphertext sets the "access_token_ciphertext" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableAccessTokenCiphertext(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetAccessTokenCiphertext(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SiteUpdateOne) SetEnabled(v bool) *SiteUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableEnabled(v *bool) *SiteUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCheckinEnabled sets the "checkin_enabled" field.
func (_u *SiteUpdateOne) SetCheckinEnabled(v bool) *SiteUpdateOne {
	_u.mutation.SetCheckinEnabled(v)
	return _u
}

// SetNillableCheckinEnabled sets the "checkin_enabled" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableCheckinEnabled(v *bool) *SiteUpdateOne {
	if v != nil {
		_u.SetCheckinEnabled(*v)
	}
	return _u
}

// SetAnnouncementEnabled sets the "announcement_enabled" field.
func (_u *SiteUpdateOne) SetAnnouncementEnabled(v bool) *SiteUpdateOne {
	_u.mutation.SetAnnouncementEnabled(v)
	return _u
}

// SetNillableAnnouncementEnabled sets the "announcement_enabled" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableAnnouncementEnabled(v *bool) *SiteUpdateOne {
	if v != nil {
		_u.SetAnnouncementEnabled(*v)
	}
	return _u
}

// SetCheckinCron sets the "checkin_cron" field.
func (_u *SiteUpdateOne) SetCheckinCron(v string) *SiteUpdateOne {
	_u.mutation.SetCheckinCron(v)
	return _u
}

// SetNillableCheckinCron sets the "checkin_cron" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableCheckinCron(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetCheckinCron(*v)
	}
	return _u
}

// SetAnnouncementCron sets the "announcement_cron" field.
func (_u *SiteUpdateOne) SetAnnouncementCron(v string) *SiteUpdateOne {
	_u.mutation.SetAnnouncementCron(v)
	return _u
}

// SetNillableAnnouncementCron sets the "announcement_cron" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableAnnouncementCron(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetAnnouncementCron(*v)
	}
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *SiteUpdateOne) SetTimezone(v string) *SiteUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableTimezone(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *SiteUpdateOne) SetConsecutiveFailures(v int) *SiteUpdateOne {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableConsecutiveFailures(v *int) *SiteUpdateOne {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *SiteUpdateOne) AddConsecutiveFailures(v int) *SiteUpdateOne {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SiteUpdateOne) SetUpdatedAt(v time.Time) *SiteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableUpdatedAt(v *time.Time) *SiteUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddCheckinRunIDs adds the "checkin_runs" edge to the CheckinRun entity by IDs.
func (_u *SiteUpdateOne) AddCheckinRunIDs(ids ...string) *SiteUpdateOne {
	_u.mutation.AddCheckinRunIDs(ids...)
	return _u
}

// AddCheckinRuns adds the "checkin_runs" edges to the CheckinRun entity.
func (_u *SiteUpdateOne) AddCheckinRuns(v ...*CheckinRun) *SiteUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCheckinRunIDs(ids...)
}

// AddAnnouncementSyncRunIDs adds the "announcement_sync_runs" edge to the AnnouncementSyncRun entity by IDs.
func (_u *SiteUpdateOne) AddAnnouncementSyncRunIDs(ids ...string) *SiteUpdateOne {
	_u.mutation.AddAnnouncementSyncRunIDs(ids...)
	return _u
}

// AddAnnouncementSyncRuns adds the "announcement_sync_runs" edges to the AnnouncementSyncRun entity.
func (_u *SiteUpdateOne) AddAnnouncementSyncRuns(v ...*AnnouncementSyncRun) *SiteUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnnouncementSyncRunIDs(ids...)
}

// AddAnnouncementIDs adds the "announcements" edge to the Announcement entity by IDs.
func (_u *SiteUpdateOne) AddAnnouncementIDs(ids ...string) *SiteUpdateOne {
	_u.mutation.AddAnnouncementIDs(ids...)
	return _u
}

// AddAnnouncements adds the "announcements" edges to the Announcement entity.
func (_u *SiteUpdateOne) AddAnnouncements(v ...*Announcement) *SiteUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnnouncementIDs(ids...)
}

// Mutation returns the SiteMutation object of the builder.
func (_u *SiteUpdateOne) Mutation() *SiteMutation {
	return _u.mutation
}

// ClearCheckinRuns clears all "checkin_runs" edges to the CheckinRun entity.
func (_u *SiteUpdateOne) ClearCheckinRuns() *SiteUpdateOne {
	_u.mutation.ClearCheckinRuns()
	return _u
}

// RemoveCheckinRunIDs removes the "checkin_runs" edge to CheckinRun entities by IDs.
func (_u *SiteUpdateOne) RemoveCheckinRunIDs(ids ...string) *SiteUpdateOne {
	_u.mutation.RemoveCheckinRunIDs(ids...)
	return _u
}

// RemoveCheckinRuns removes "checkin_runs" edges to CheckinRun entities.
func (_u *SiteUpdateOne) RemoveCheckinRuns(v ...*CheckinRun) *SiteUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCheckinRunIDs(ids...)
}

// ClearAnnouncementSyncRuns clears all "announcement_sync_runs" edges to the AnnouncementSyncRun entity.
func (_u *SiteUpdateOne) ClearAnnouncementSyncRuns() *SiteUpdateOne {
	_u.mutation.ClearAnnouncementSyncRuns()
	return _u
}

// RemoveAnnouncementSyncRunIDs removes the "announcement_sync_runs" edge to AnnouncementSyncRun entities by IDs.
func (_u *SiteUpdateOne) RemoveAnnouncementSyncRunIDs(ids ...string) *SiteUpdateOne {
	_u.mutation.RemoveAnnouncementSyncRunIDs(ids...)
	return _u
}

// RemoveAnnouncementSyncRuns removes "announcement_sync_runs" edges to AnnouncementSyncRun entities.
func (_u *SiteUpdateOne) RemoveAnnouncementSyncRuns(v ...*AnnouncementSyncRun) *SiteUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnnouncementSyncRunIDs(ids...)
}

// ClearAnnouncements clears all "announcements" edges to the Announcement entity.
func (_u *SiteUpdateOne) ClearAnnouncements() *SiteUpdateOne {
	_u.mutation.ClearAnnouncements()
	return _u
}

// RemoveAnnouncementIDs removes the "announcements" edge to Announcement entities by IDs.
func (_u *SiteUpdateOne) RemoveAnnouncementIDs(ids ...string) *SiteUpdateOne {
	_u.mutation.RemoveAnnouncementIDs(ids...)
	return _u
}

// RemoveAnnouncements removes "announcements" edges to Announcement entities.
func (_u *SiteUpdateOne) RemoveAnnouncements(v ...*Announcement) *SiteUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnnouncementIDs(ids...)
}

// Where appends a list predicates to the SiteUpdate builder.
func (_u *SiteUpdateOne) Where(ps ...predicate.Site) *SiteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SiteUpdateOne) Select(field string, fields ...string) *SiteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Site entity.
func (_u *SiteUpdateOne) Save(ctx context.Context) (*Site, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SiteUpdateOne) SaveX(ctx context.Context) *Site {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SiteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SiteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SiteUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := site.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Site.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Adapter(); ok {
		if err := site.AdapterValidator(v); err != nil {
			return &ValidationError{Name: "adapter", err: fmt.Errorf(`ent: validator failed for field "Site.adapter": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := site.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Site.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CheckinCron(); ok {
		if err := site.CheckinCronValidator(v); err != nil {
			return &ValidationError{Name: "checkin_cron", err: fmt.Errorf(`ent: validator failed for field "Site.checkin_cron": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AnnouncementCron(); ok {
		if err := site.AnnouncementCronValidator(v); err != nil {
			return &ValidationError{Name: "announcement_cron", err: fmt.Errorf(`ent: validator failed for field "Site.announcement_cron": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timezone(); ok {
		if err := site.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "Site.timezone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConsecutiveFailures(); ok {
		if err := site.ConsecutiveFailuresValidator(v); err != nil {
			return &ValidationError{Name: "consecutive_failures", err: fmt.Errorf(`ent: validator failed for field "Site.consecutive_failures": %w`, err)}
		}
	}
	return nil
}

func (_u *SiteUpdateOne) sqlSave(ctx context.Context) (_node *Site, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(site.Table, site.Columns, sqlgraph.NewFieldSpec(site.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Site.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, site.FieldID)
		for _, f := range fields {
			if !site.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != site.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(site.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(site.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Adapter(); ok {
		_spec.SetField(site.FieldAdapter, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(site.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessTokenCiphertext(); ok {
		_spec.SetField(site.FieldAccessTokenCiphertext, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(site.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CheckinEnabled(); ok {
		_spec.SetField(site.FieldCheckinEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AnnouncementEnabled(); ok {
		_spec.SetField(site.FieldAnnouncementEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CheckinCron(); ok {
		_spec.SetField(site.FieldCheckinCron, field.TypeString, value)
	}
	if value, ok := _u.mutation.AnnouncementCron(); ok {
		_spec.SetField(site.FieldAnnouncementCron, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(site.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(site.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(site.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(site.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CheckinRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.CheckinRunsTable,
			Columns: []string{site.CheckinRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkinrun.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCheckinRunsIDs(); len(nodes) > 0 && !_u.mutation.CheckinRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.CheckinRunsTable,
			Columns: []string{site.CheckinRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkinrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CheckinRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.CheckinRunsTable,
			Columns: []string{site.CheckinRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(checkinrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnnouncementSyncRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.AnnouncementSyncRunsTable,
			Columns: []string{site.AnnouncementSyncRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementsyncrun.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnnouncementSyncRunsIDs(); len(nodes) > 0 && !_u.mutation.AnnouncementSyncRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.AnnouncementSyncRunsTable,
			Columns: []string{site.AnnouncementSyncRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementsyncrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnnouncementSyncRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.AnnouncementSyncRunsTable,
			Columns: []string{site.AnnouncementSyncRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementsyncrun.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnnouncementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.AnnouncementsTable,
			Columns: []string{site.AnnouncementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnnouncementsIDs(); len(nodes) > 0 && !_u.mutation.AnnouncementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.AnnouncementsTable,
			Columns: []string{site.AnnouncementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnnouncementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.AnnouncementsTable,
			Columns: []string{site.AnnouncementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Site{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{site.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
