// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Announcement is the predicate function for announcement builders.
type Announcement func(*sql.Selector)

// AnnouncementSyncRun is the predicate function for announcementsyncrun builders.
type AnnouncementSyncRun func(*sql.Selector)

// CheckinRun is the predicate function for checkinrun builders.
type CheckinRun func(*sql.Selector)

// Site is the predicate function for site builders.
type Site func(*sql.Selector)
