// Code generated by ent, DO NOT EDIT.

package announcementsyncrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/elykia/apihub/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldContainsFold(FieldID, id))
}

// SiteID applies equality check predicate on the "site_id" field. It's identical to SiteIDEQ.
func SiteID(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEQ(FieldSiteID, v))
}

// AddedCount applies equality check predicate on the "added_count" field. It's identical to AddedCountEQ.
func AddedCount(v int) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEQ(FieldAddedCount, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEQ(FieldMessage, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEQ(FieldFinishedAt, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEQ(FieldRequestID, v))
}

// SiteIDEQ applies the EQ predicate on the "site_id" field.
func SiteIDEQ(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEQ(FieldSiteID, v))
}

// SiteIDNEQ applies the NEQ predicate on the "site_id" field.
func SiteIDNEQ(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNEQ(FieldSiteID, v))
}

// SiteIDIn applies the In predicate on the "site_id" field.
func SiteIDIn(vs ...string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldIn(FieldSiteID, vs...))
}

// SiteIDNotIn applies the NotIn predicate on the "site_id" field.
func SiteIDNotIn(vs ...string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNotIn(FieldSiteID, vs...))
}

// SiteIDGT applies the GT predicate on the "site_id" field.
func SiteIDGT(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldGT(FieldSiteID, v))
}

// SiteIDGTE applies the GTE predicate on the "site_id" field.
func SiteIDGTE(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldGTE(FieldSiteID, v))
}

// SiteIDLT applies the LT predicate on the "site_id" field.
func SiteIDLT(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldLT(FieldSiteID, v))
}

// SiteIDLTE applies the LTE predicate on the "site_id" field.
func SiteIDLTE(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldLTE(FieldSiteID, v))
}

// SiteIDContains applies the Contains predicate on the "site_id" field.
func SiteIDContains(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldContains(FieldSiteID, v))
}

// SiteIDHasPrefix applies the HasPrefix predicate on the "site_id" field.
func SiteIDHasPrefix(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldHasPrefix(FieldSiteID, v))
}

// SiteIDHasSuffix applies the HasSuffix predicate on the "site_id" field.
func SiteIDHasSuffix(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldHasSuffix(FieldSiteID, v))
}

// SiteIDEqualFold applies the EqualFold predicate on the "site_id" field.
func SiteIDEqualFold(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEqualFold(FieldSiteID, v))
}

// SiteIDContainsFold applies the ContainsFold predicate on the "site_id" field.
func SiteIDContainsFold(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldContainsFold(FieldSiteID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNotIn(FieldStatus, vs...))
}

// AddedCountEQ applies the EQ predicate on the "added_count" field.
func AddedCountEQ(v int) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEQ(FieldAddedCount, v))
}

// AddedCountNEQ applies the NEQ predicate on the "added_count" field.
func AddedCountNEQ(v int) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNEQ(FieldAddedCount, v))
}

// AddedCountIn applies the In predicate on the "added_count" field.
func AddedCountIn(vs ...int) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldIn(FieldAddedCount, vs...))
}

// AddedCountNotIn applies the NotIn predicate on the "added_count" field.
func AddedCountNotIn(vs ...int) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNotIn(FieldAddedCount, vs...))
}

// AddedCountGT applies the GT predicate on the "added_count" field.
func AddedCountGT(v int) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldGT(FieldAddedCount, v))
}

// AddedCountGTE applies the GTE predicate on the "added_count" field.
func AddedCountGTE(v int) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldGTE(FieldAddedCount, v))
}

// AddedCountLT applies the LT predicate on the "added_count" field.
func AddedCountLT(v int) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldLT(FieldAddedCount, v))
}

// AddedCountLTE applies the LTE predicate on the "added_count" field.
func AddedCountLTE(v int) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldLTE(FieldAddedCount, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldContainsFold(FieldMessage, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldLTE(FieldStartedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNotNull(FieldFinishedAt))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.FieldContainsFold(FieldRequestID, v))
}

// HasSite applies the HasEdge predicate on the "site" edge.
func HasSite() predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SiteTable, SiteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSiteWith applies the HasEdge predicate on the "site" edge with a given conditions (other predicates).
func HasSiteWith(preds ...predicate.Site) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(func(s *sql.Selector) {
		step := newSiteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AnnouncementSyncRun) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AnnouncementSyncRun) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AnnouncementSyncRun) predicate.AnnouncementSyncRun {
	return predicate.AnnouncementSyncRun(sql.NotPredicates(p))
}
