// Code generated by ent, DO NOT EDIT.

package site

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the site type in the database.
	Label = "site"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldAdapter holds the string denoting the adapter field in the database.
	FieldAdapter = "adapter"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAccessTokenCiphertext holds the string denoting the access_token_ciphertext field in the database.
	FieldAccessTokenCiphertext = "access_token_ciphertext"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCheckinEnabled holds the string denoting the checkin_enabled field in the database.
	FieldCheckinEnabled = "checkin_enabled"
	// FieldAnnouncementEnabled holds the string denoting the announcement_enabled field in the database.
	FieldAnnouncementEnabled = "announcement_enabled"
	// FieldCheckinCron holds the string denoting the checkin_cron field in the database.
	FieldCheckinCron = "checkin_cron"
	// FieldAnnouncementCron holds the string denoting the announcement_cron field in the database.
	FieldAnnouncementCron = "announcement_cron"
	// FieldTimezone holds the string denoting the timezone field in the database.
	FieldTimezone = "timezone"
	// FieldConsecutiveFailures holds the string denoting the consecutive_failures field in the database.
	FieldConsecutiveFailures = "consecutive_failures"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCheckinRuns holds the string denoting the checkin_runs edge name in mutations.
	EdgeCheckinRuns = "checkin_runs"
	// EdgeAnnouncementSyncRuns holds the string denoting the announcement_sync_runs edge name in mutations.
	EdgeAnnouncementSyncRuns = "announcement_sync_runs"
	// EdgeAnnouncements holds the string denoting the announcements edge name in mutations.
	EdgeAnnouncements = "announcements"
	// Table holds the table name of the site in the database.
	Table = "sites"
	// CheckinRunsTable is the table that holds the checkin_runs relation/edge.
	CheckinRunsTable = "checkin_runs"
	// CheckinRunsInverseTable is the table name for the CheckinRun entity.
	// It exists in this package in order to avoid circular dependency with the "checkinrun" package.
	CheckinRunsInverseTable = "checkin_runs"
	// CheckinRunsColumn is the table column denoting the checkin_runs relation/edge.
	CheckinRunsColumn = "site_id"
	// AnnouncementSyncRunsTable is the table that holds the announcement_sync_runs relation/edge.
	AnnouncementSyncRunsTable = "announcement_sync_runs"
	// AnnouncementSyncRunsInverseTable is the table name for the AnnouncementSyncRun entity.
	// It exists in this package in order to avoid circular dependency with the "announcementsyncrun" package.
	AnnouncementSyncRunsInverseTable = "announcement_sync_runs"
	// AnnouncementSyncRunsColumn is the table column denoting the announcement_sync_runs relation/edge.
	AnnouncementSyncRunsColumn = "site_id"
	// AnnouncementsTable is the table that holds the announcements relation/edge.
	AnnouncementsTable = "announcements"
	// AnnouncementsInverseTable is the table name for the Announcement entity.
	// It exists in this package in order to avoid circular dependency with the "announcement" package.
	AnnouncementsInverseTable = "announcements"
	// AnnouncementsColumn is the table column denoting the announcements relation/edge.
	AnnouncementsColumn = "site_id"
)

// Columns holds all SQL columns for site fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldBaseURL,
	FieldAdapter,
	FieldUserID,
	FieldAccessTokenCiphertext,
	FieldEnabled,
	FieldCheckinEnabled,
	FieldAnnouncementEnabled,
	FieldCheckinCron,
	FieldAnnouncementCron,
	FieldTimezone,
	FieldConsecutiveFailures,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCheckinEnabled holds the default value on creation for the "checkin_enabled" field.
	DefaultCheckinEnabled bool
	// DefaultAnnouncementEnabled holds the default value on creation for the "announcement_enabled" field.
	DefaultAnnouncementEnabled bool
	// CheckinCronValidator is a validator for the "checkin_cron" field. It is called by the builders before save.
	CheckinCronValidator func(string) error
	// AnnouncementCronValidator is a validator for the "announcement_cron" field. It is called by the builders before save.
	AnnouncementCronValidator func(string) error
	// TimezoneValidator is a validator for the "timezone" field. It is called by the builders before save.
	TimezoneValidator func(string) error
	// DefaultConsecutiveFailures holds the default value on creation for the "consecutive_failures" field.
	DefaultConsecutiveFailures int
	// ConsecutiveFailuresValidator is a validator for the "consecutive_failures" field. It is called by the builders before save.
	ConsecutiveFailuresValidator func(int) error
)

// Adapter defines the type for the "adapter" enum field.
type Adapter string

// Adapter values.
const (
	AdapterNewAPI  Adapter = "new-api"
	AdapterSub2api Adapter = "sub2api"
	AdapterZenAPI  Adapter = "zen-api"
)

func (a Adapter) String() string {
	return string(a)
}

// AdapterValidator is a validator for the "adapter" field enum values. It is called by the builders before save.
func AdapterValidator(a Adapter) error {
	switch a {
	case AdapterNewAPI, AdapterSub2api, AdapterZenAPI:
		return nil
	default:
		return fmt.Errorf("site: invalid enum value for adapter field: %q", a)
	}
}

// OrderOption defines the ordering options for the Site queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByAdapter orders the results by the adapter field.
func ByAdapter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdapter, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAccessTokenCiphertext orders the results by the access_token_ciphertext field.
func ByAccessTokenCiphertext(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessTokenCiphertext, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCheckinEnabled orders the results by the checkin_enabled field.
func ByCheckinEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckinEnabled, opts...).ToFunc()
}

// ByAnnouncementEnabled orders the results by the announcement_enabled field.
func ByAnnouncementEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnnouncementEnabled, opts...).ToFunc()
}

// ByCheckinCron orders the results by the checkin_cron field.
func ByCheckinCron(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckinCron, opts...).ToFunc()
}

// ByAnnouncementCron orders the results by the announcement_cron field.
func ByAnnouncementCron(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnnouncementCron, opts...).ToFunc()
}

// ByTimezone orders the results by the timezone field.
func ByTimezone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimezone, opts...).ToFunc()
}

// ByConsecutiveFailures orders the results by the consecutive_failures field.
func ByConsecutiveFailures(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsecutiveFailures, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCheckinRunsCount orders the results by checkin_runs count.
func ByCheckinRunsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCheckinRunsStep(), opts...)
	}
}

// ByCheckinRuns orders the results by checkin_runs terms.
func ByCheckinRuns(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCheckinRunsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAnnouncementSyncRunsCount orders the results by announcement_sync_runs count.
func ByAnnouncementSyncRunsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAnnouncementSyncRunsStep(), opts...)
	}
}

// ByAnnouncementSyncRuns orders the results by announcement_sync_runs terms.
func ByAnnouncementSyncRuns(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAnnouncementSyncRunsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAnnouncementsCount orders the results by announcements count.
func ByAnnouncementsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAnnouncementsStep(), opts...)
	}
}

// ByAnnouncements orders the results by announcements terms.
func ByAnnouncements(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAnnouncementsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCheckinRunsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CheckinRunsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CheckinRunsTable, CheckinRunsColumn),
	)
}
func newAnnouncementSyncRunsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AnnouncementSyncRunsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AnnouncementSyncRunsTable, AnnouncementSyncRunsColumn),
	)
}
func newAnnouncementsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AnnouncementsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AnnouncementsTable, AnnouncementsColumn),
	)
}
