// Code generated by ent, DO NOT EDIT.

package site

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/elykia/apihub/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Site {
	return predicate.Site(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Site {
	return predicate.Site(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldName, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldBaseURL, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldUserID, v))
}

// AccessTokenCiphertext applies equality check predicate on the "access_token_ciphertext" field. It's identical to AccessTokenCiphertextEQ.
func AccessTokenCiphertext(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldAccessTokenCiphertext, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldEnabled, v))
}

// CheckinEnabled applies equality check predicate on the "checkin_enabled" field. It's identical to CheckinEnabledEQ.
func CheckinEnabled(v bool) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldCheckinEnabled, v))
}

// AnnouncementEnabled applies equality check predicate on the "announcement_enabled" field. It's identical to AnnouncementEnabledEQ.
func AnnouncementEnabled(v bool) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldAnnouncementEnabled, v))
}

// CheckinCron applies equality check predicate on the "checkin_cron" field. It's identical to CheckinCronEQ.
func CheckinCron(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldCheckinCron, v))
}

// AnnouncementCron applies equality check predicate on the "announcement_cron" field. It's identical to AnnouncementCronEQ.
func AnnouncementCron(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldAnnouncementCron, v))
}

// Timezone applies equality check predicate on the "timezone" field. It's identical to TimezoneEQ.
func Timezone(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldTimezone, v))
}

// ConsecutiveFailures applies equality check predicate on the "consecutive_failures" field. It's identical to ConsecutiveFailuresEQ.
func ConsecutiveFailures(v int) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Site {
	return predicate.Site(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Site {
	return predicate.Site(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Site {
	return predicate.Site(sql.FieldContainsFold(FieldName, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.Site {
	return predicate.Site(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.Site {
	return predicate.Site(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.Site {
	return predicate.Site(sql.FieldContainsFold(FieldBaseURL, v))
}

// AdapterEQ applies the EQ predicate on the "adapter" field.
func AdapterEQ(v Adapter) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldAdapter, v))
}

// AdapterNEQ applies the NEQ predicate on the "adapter" field.
func AdapterNEQ(v Adapter) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldAdapter, v))
}

// AdapterIn applies the In predicate on the "adapter" field.
func AdapterIn(vs ...Adapter) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldAdapter, vs...))
}

// AdapterNotIn applies the NotIn predicate on the "adapter" field.
func AdapterNotIn(vs ...Adapter) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldAdapter, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.Site {
	return predicate.Site(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.Site {
	return predicate.Site(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.Site {
	return predicate.Site(sql.FieldContainsFold(FieldUserID, v))
}

// AccessTokenCiphertextEQ applies the EQ predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextNEQ applies the NEQ predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextNEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextIn applies the In predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldAccessTokenCiphertext, vs...))
}

// AccessTokenCiphertextNotIn applies the NotIn predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextNotIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldAccessTokenCiphertext, vs...))
}

// AccessTokenCiphertextGT applies the GT predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextGT(v string) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextGTE applies the GTE predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextGTE(v string) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextLT applies the LT predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextLT(v string) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextLTE applies the LTE predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextLTE(v string) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextContains applies the Contains predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextContains(v string) predicate.Site {
	return predicate.Site(sql.FieldContains(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextHasPrefix applies the HasPrefix predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextHasPrefix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasPrefix(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextHasSuffix applies the HasSuffix predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextHasSuffix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasSuffix(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextEqualFold applies the EqualFold predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextEqualFold(v string) predicate.Site {
	return predicate.Site(sql.FieldEqualFold(FieldAccessTokenCiphertext, v))
}

// AccessTokenCiphertextContainsFold applies the ContainsFold predicate on the "access_token_ciphertext" field.
func AccessTokenCiphertextContainsFold(v string) predicate.Site {
	return predicate.Site(sql.FieldContainsFold(FieldAccessTokenCiphertext, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldEnabled, v))
}

// CheckinEnabledEQ applies the EQ predicate on the "checkin_enabled" field.
func CheckinEnabledEQ(v bool) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldCheckinEnabled, v))
}

// CheckinEnabledNEQ applies the NEQ predicate on the "checkin_enabled" field.
func CheckinEnabledNEQ(v bool) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldCheckinEnabled, v))
}

// AnnouncementEnabledEQ applies the EQ predicate on the "announcement_enabled" field.
func AnnouncementEnabledEQ(v bool) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldAnnouncementEnabled, v))
}

// AnnouncementEnabledNEQ applies the NEQ predicate on the "announcement_enabled" field.
func AnnouncementEnabledNEQ(v bool) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldAnnouncementEnabled, v))
}

// CheckinCronEQ applies the EQ predicate on the "checkin_cron" field.
func CheckinCronEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldCheckinCron, v))
}

// CheckinCronNEQ applies the NEQ predicate on the "checkin_cron" field.
func CheckinCronNEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldCheckinCron, v))
}

// CheckinCronIn applies the In predicate on the "checkin_cron" field.
func CheckinCronIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldCheckinCron, vs...))
}

// CheckinCronNotIn applies the NotIn predicate on the "checkin_cron" field.
func CheckinCronNotIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldCheckinCron, vs...))
}

// CheckinCronGT applies the GT predicate on the "checkin_cron" field.
func CheckinCronGT(v string) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldCheckinCron, v))
}

// CheckinCronGTE applies the GTE predicate on the "checkin_cron" field.
func CheckinCronGTE(v string) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldCheckinCron, v))
}

// CheckinCronLT applies the LT predicate on the "checkin_cron" field.
func CheckinCronLT(v string) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldCheckinCron, v))
}

// CheckinCronLTE applies the LTE predicate on the "checkin_cron" field.
func CheckinCronLTE(v string) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldCheckinCron, v))
}

// CheckinCronContains applies the Contains predicate on the "checkin_cron" field.
func CheckinCronContains(v string) predicate.Site {
	return predicate.Site(sql.FieldContains(FieldCheckinCron, v))
}

// CheckinCronHasPrefix applies the HasPrefix predicate on the "checkin_cron" field.
func CheckinCronHasPrefix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasPrefix(FieldCheckinCron, v))
}

// CheckinCronHasSuffix applies the HasSuffix predicate on the "checkin_cron" field.
func CheckinCronHasSuffix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasSuffix(FieldCheckinCron, v))
}

// CheckinCronEqualFold applies the EqualFold predicate on the "checkin_cron" field.
func CheckinCronEqualFold(v string) predicate.Site {
	return predicate.Site(sql.FieldEqualFold(FieldCheckinCron, v))
}

// CheckinCronContainsFold applies the ContainsFold predicate on the "checkin_cron" field.
func CheckinCronContainsFold(v string) predicate.Site {
	return predicate.Site(sql.FieldContainsFold(FieldCheckinCron, v))
}

// AnnouncementCronEQ applies the EQ predicate on the "announcement_cron" field.
func AnnouncementCronEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldAnnouncementCron, v))
}

// AnnouncementCronNEQ applies the NEQ predicate on the "announcement_cron" field.
func AnnouncementCronNEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldAnnouncementCron, v))
}

// AnnouncementCronIn applies the In predicate on the "announcement_cron" field.
func AnnouncementCronIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldAnnouncementCron, vs...))
}

// AnnouncementCronNotIn applies the NotIn predicate on the "announcement_cron" field.
func AnnouncementCronNotIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldAnnouncementCron, vs...))
}

// AnnouncementCronGT applies the GT predicate on the "announcement_cron" field.
func AnnouncementCronGT(v string) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldAnnouncementCron, v))
}

// AnnouncementCronGTE applies the GTE predicate on the "announcement_cron" field.
func AnnouncementCronGTE(v string) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldAnnouncementCron, v))
}

// AnnouncementCronLT applies the LT predicate on the "announcement_cron" field.
func AnnouncementCronLT(v string) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldAnnouncementCron, v))
}

// AnnouncementCronLTE applies the LTE predicate on the "announcement_cron" field.
func AnnouncementCronLTE(v string) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldAnnouncementCron, v))
}

// AnnouncementCronContains applies the Contains predicate on the "announcement_cron" field.
func AnnouncementCronContains(v string) predicate.Site {
	return predicate.Site(sql.FieldContains(FieldAnnouncementCron, v))
}

// AnnouncementCronHasPrefix applies the HasPrefix predicate on the "announcement_cron" field.
func AnnouncementCronHasPrefix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasPrefix(FieldAnnouncementCron, v))
}

// AnnouncementCronHasSuffix applies the HasSuffix predicate on the "announcement_cron" field.
func AnnouncementCronHasSuffix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasSuffix(FieldAnnouncementCron, v))
}

// AnnouncementCronEqualFold applies the EqualFold predicate on the "announcement_cron" field.
func AnnouncementCronEqualFold(v string) predicate.Site {
	return predicate.Site(sql.FieldEqualFold(FieldAnnouncementCron, v))
}

// AnnouncementCronContainsFold applies the ContainsFold predicate on the "announcement_cron" field.
func AnnouncementCronContainsFold(v string) predicate.Site {
	return predicate.Site(sql.FieldContainsFold(FieldAnnouncementCron, v))
}

// TimezoneEQ applies the EQ predicate on the "timezone" field.
func TimezoneEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldTimezone, v))
}

// TimezoneNEQ applies the NEQ predicate on the "timezone" field.
func TimezoneNEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldTimezone, v))
}

// TimezoneIn applies the In predicate on the "timezone" field.
func TimezoneIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldTimezone, vs...))
}

// TimezoneNotIn applies the NotIn predicate on the "timezone" field.
func TimezoneNotIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldTimezone, vs...))
}

// TimezoneGT applies the GT predicate on the "timezone" field.
func TimezoneGT(v string) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldTimezone, v))
}

// TimezoneGTE applies the GTE predicate on the "timezone" field.
func TimezoneGTE(v string) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldTimezone, v))
}

// TimezoneLT applies the LT predicate on the "timezone" field.
func TimezoneLT(v string) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldTimezone, v))
}

// TimezoneLTE applies the LTE predicate on the "timezone" field.
func TimezoneLTE(v string) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldTimezone, v))
}

// TimezoneContains applies the Contains predicate on the "timezone" field.
func TimezoneContains(v string) predicate.Site {
	return predicate.Site(sql.FieldContains(FieldTimezone, v))
}

// TimezoneHasPrefix applies the HasPrefix predicate on the "timezone" field.
func TimezoneHasPrefix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasPrefix(FieldTimezone, v))
}

// TimezoneHasSuffix applies the HasSuffix predicate on the "timezone" field.
func TimezoneHasSuffix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasSuffix(FieldTimezone, v))
}

// TimezoneEqualFold applies the EqualFold predicate on the "timezone" field.
func TimezoneEqualFold(v string) predicate.Site {
	return predicate.Site(sql.FieldEqualFold(FieldTimezone, v))
}

// TimezoneContainsFold applies the ContainsFold predicate on the "timezone" field.
func TimezoneContainsFold(v string) predicate.Site {
	return predicate.Site(sql.FieldContainsFold(FieldTimezone, v))
}

// ConsecutiveFailuresEQ applies the EQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresEQ(v int) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresNEQ applies the NEQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNEQ(v int) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresIn applies the In predicate on the "consecutive_failures" field.
func ConsecutiveFailuresIn(vs ...int) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresNotIn applies the NotIn predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNotIn(vs ...int) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresGT applies the GT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGT(v int) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresGTE applies the GTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGTE(v int) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLT applies the LT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLT(v int) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLTE applies the LTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLTE(v int) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldConsecutiveFailures, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCheckinRuns applies the HasEdge predicate on the "checkin_runs" edge.
func HasCheckinRuns() predicate.Site {
	return predicate.Site(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CheckinRunsTable, CheckinRunsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCheckinRunsWith applies the HasEdge predicate on the "checkin_runs" edge with a given conditions (other predicates).
func HasCheckinRunsWith(preds ...predicate.CheckinRun) predicate.Site {
	return predicate.Site(func(s *sql.Selector) {
		step := newCheckinRunsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAnnouncementSyncRuns applies the HasEdge predicate on the "announcement_sync_runs" edge.
func HasAnnouncementSyncRuns() predicate.Site {
	return predicate.Site(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AnnouncementSyncRunsTable, AnnouncementSyncRunsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAnnouncementSyncRunsWith applies the HasEdge predicate on the "announcement_sync_runs" edge with a given conditions (other predicates).
func HasAnnouncementSyncRunsWith(preds ...predicate.AnnouncementSyncRun) predicate.Site {
	return predicate.Site(func(s *sql.Selector) {
		step := newAnnouncementSyncRunsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAnnouncements applies the HasEdge predicate on the "announcements" edge.
func HasAnnouncements() predicate.Site {
	return predicate.Site(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AnnouncementsTable, AnnouncementsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAnnouncementsWith applies the HasEdge predicate on the "announcements" edge with a given conditions (other predicates).
func HasAnnouncementsWith(preds ...predicate.Announcement) predicate.Site {
	return predicate.Site(func(s *sql.Selector) {
		step := newAnnouncementsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Site) predicate.Site {
	return predicate.Site(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Site) predicate.Site {
	return predicate.Site(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Site) predicate.Site {
	return predicate.Site(sql.NotPredicates(p))
}
