// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AnnouncementsColumns holds the columns for the "announcements" table.
	AnnouncementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"status", "notice"}},
		{Name: "fingerprint", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "kind", Type: field.TypeString, Size: 32, Default: "default"},
		{Name: "extra", Type: field.TypeString, Nullable: true},
		{Name: "published_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "first_seen_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "last_seen_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "read_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "site_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// AnnouncementsTable holds the schema information for the "announcements" table.
	AnnouncementsTable = &schema.Table{
		Name:       "announcements",
		Columns:    AnnouncementsColumns,
		PrimaryKey: []*schema.Column{AnnouncementsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "announcements_sites_announcements",
				Columns:    []*schema.Column{AnnouncementsColumns[10]},
				RefColumns: []*schema.Column{SitesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "announcement_site_id_fingerprint",
				Unique:  true,
				Columns: []*schema.Column{AnnouncementsColumns[10], AnnouncementsColumns[2]},
			},
		},
	}
	// AnnouncementSyncRunsColumns holds the columns for the "announcement_sync_runs" table.
	AnnouncementSyncRunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"running", "success", "partial", "failed"}},
		{Name: "added_count", Type: field.TypeInt, Default: 0},
		{Name: "message", Type: field.TypeString, Default: ""},
		{Name: "started_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "request_id", Type: field.TypeString},
		{Name: "site_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// AnnouncementSyncRunsTable holds the schema information for the "announcement_sync_runs" table.
	AnnouncementSyncRunsTable = &schema.Table{
		Name:       "announcement_sync_runs",
		Columns:    AnnouncementSyncRunsColumns,
		PrimaryKey: []*schema.Column{AnnouncementSyncRunsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "announcement_sync_runs_sites_announcement_sync_runs",
				Columns:    []*schema.Column{AnnouncementSyncRunsColumns[7]},
				RefColumns: []*schema.Column{SitesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CheckinRunsColumns holds the columns for the "checkin_runs" table.
	CheckinRunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "local_date", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"running", "success", "already_checked", "manual_required", "failed", "skipped"}},
		{Name: "reward_value", Type: field.TypeInt64, Nullable: true},
		{Name: "message", Type: field.TypeString, Default: ""},
		{Name: "error_code", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "attempt_count", Type: field.TypeInt, Default: 1},
		{Name: "started_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "request_id", Type: field.TypeString},
		{Name: "site_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// CheckinRunsTable holds the schema information for the "checkin_runs" table.
	CheckinRunsTable = &schema.Table{
		Name:       "checkin_runs",
		Columns:    CheckinRunsColumns,
		PrimaryKey: []*schema.Column{CheckinRunsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "checkin_runs_sites_checkin_runs",
				Columns:    []*schema.Column{CheckinRunsColumns[10]},
				RefColumns: []*schema.Column{SitesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "checkinrun_site_id_local_date",
				Unique:  true,
				Columns: []*schema.Column{CheckinRunsColumns[10], CheckinRunsColumns[1]},
			},
		},
	}
	// SitesColumns holds the columns for the "sites" table.
	SitesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "name", Type: field.TypeString, Size: 80},
		{Name: "base_url", Type: field.TypeString},
		{Name: "adapter", Type: field.TypeEnum, Enums: []string{"new-api", "sub2api", "zen-api"}},
		{Name: "user_id", Type: field.TypeString, Size: 128},
		{Name: "access_token_ciphertext", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "checkin_enabled", Type: field.TypeBool, Default: true},
		{Name: "announcement_enabled", Type: field.TypeBool, Default: true},
		{Name: "checkin_cron", Type: field.TypeString, Size: 100},
		{Name: "announcement_cron", Type: field.TypeString, Size: 100},
		{Name: "timezone", Type: field.TypeString, Size: 100},
		{Name: "consecutive_failures", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// SitesTable holds the schema information for the "sites" table.
	SitesTable = &schema.Table{
		Name:       "sites",
		Columns:    SitesColumns,
		PrimaryKey: []*schema.Column{SitesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AnnouncementsTable,
		AnnouncementSyncRunsTable,
		CheckinRunsTable,
		SitesTable,
	}
)

func init() {
	AnnouncementsTable.ForeignKeys[0].RefTable = SitesTable
	AnnouncementsTable.Annotation = &entsql.Annotation{
		Table: "announcements",
	}
	AnnouncementSyncRunsTable.ForeignKeys[0].RefTable = SitesTable
	AnnouncementSyncRunsTable.Annotation = &entsql.Annotation{
		Table: "announcement_sync_runs",
	}
	CheckinRunsTable.ForeignKeys[0].RefTable = SitesTable
	CheckinRunsTable.Annotation = &entsql.Annotation{
		Table: "checkin_runs",
	}
	SitesTable.Annotation = &entsql.Annotation{
		Table: "sites",
	}
}
