// Code generated by ent, DO NOT EDIT.

package checkinrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/elykia/apihub/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldContainsFold(FieldID, id))
}

// SiteID applies equality check predicate on the "site_id" field. It's identical to SiteIDEQ.
func SiteID(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldSiteID, v))
}

// LocalDate applies equality check predicate on the "local_date" field. It's identical to LocalDateEQ.
func LocalDate(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldLocalDate, v))
}

// RewardValue applies equality check predicate on the "reward_value" field. It's identical to RewardValueEQ.
func RewardValue(v int64) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldRewardValue, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldMessage, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldErrorCode, v))
}

// AttemptCount applies equality check predicate on the "attempt_count" field. It's identical to AttemptCountEQ.
func AttemptCount(v int) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldAttemptCount, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldFinishedAt, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldRequestID, v))
}

// SiteIDEQ applies the EQ predicate on the "site_id" field.
func SiteIDEQ(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldSiteID, v))
}

// SiteIDNEQ applies the NEQ predicate on the "site_id" field.
func SiteIDNEQ(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNEQ(FieldSiteID, v))
}

// SiteIDIn applies the In predicate on the "site_id" field.
func SiteIDIn(vs ...string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldIn(FieldSiteID, vs...))
}

// SiteIDNotIn applies the NotIn predicate on the "site_id" field.
func SiteIDNotIn(vs ...string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNotIn(FieldSiteID, vs...))
}

// SiteIDGT applies the GT predicate on the "site_id" field.
func SiteIDGT(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGT(FieldSiteID, v))
}

// SiteIDGTE applies the GTE predicate on the "site_id" field.
func SiteIDGTE(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGTE(FieldSiteID, v))
}

// SiteIDLT applies the LT predicate on the "site_id" field.
func SiteIDLT(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLT(FieldSiteID, v))
}

// SiteIDLTE applies the LTE predicate on the "site_id" field.
func SiteIDLTE(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLTE(FieldSiteID, v))
}

// SiteIDContains applies the Contains predicate on the "site_id" field.
func SiteIDContains(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldContains(FieldSiteID, v))
}

// SiteIDHasPrefix applies the HasPrefix predicate on the "site_id" field.
func SiteIDHasPrefix(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldHasPrefix(FieldSiteID, v))
}

// SiteIDHasSuffix applies the HasSuffix predicate on the "site_id" field.
func SiteIDHasSuffix(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldHasSuffix(FieldSiteID, v))
}

// SiteIDEqualFold applies the EqualFold predicate on the "site_id" field.
func SiteIDEqualFold(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEqualFold(FieldSiteID, v))
}

// SiteIDContainsFold applies the ContainsFold predicate on the "site_id" field.
func SiteIDContainsFold(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldContainsFold(FieldSiteID, v))
}

// LocalDateEQ applies the EQ predicate on the "local_date" field.
func LocalDateEQ(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldLocalDate, v))
}

// LocalDateNEQ applies the NEQ predicate on the "local_date" field.
func LocalDateNEQ(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNEQ(FieldLocalDate, v))
}

// LocalDateIn applies the In predicate on the "local_date" field.
func LocalDateIn(vs ...time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldIn(FieldLocalDate, vs...))
}

// LocalDateNotIn applies the NotIn predicate on the "local_date" field.
func LocalDateNotIn(vs ...time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNotIn(FieldLocalDate, vs...))
}

// LocalDateGT applies the GT predicate on the "local_date" field.
func LocalDateGT(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGT(FieldLocalDate, v))
}

// LocalDateGTE applies the GTE predicate on the "local_date" field.
func LocalDateGTE(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGTE(FieldLocalDate, v))
}

// LocalDateLT applies the LT predicate on the "local_date" field.
func LocalDateLT(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLT(FieldLocalDate, v))
}

// LocalDateLTE applies the LTE predicate on the "local_date" field.
func LocalDateLTE(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLTE(FieldLocalDate, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNotIn(FieldStatus, vs...))
}

// RewardValueEQ applies the EQ predicate on the "reward_value" field.
func RewardValueEQ(v int64) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldRewardValue, v))
}

// RewardValueNEQ applies the NEQ predicate on the "reward_value" field.
func RewardValueNEQ(v int64) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNEQ(FieldRewardValue, v))
}

// RewardValueIn applies the In predicate on the "reward_value" field.
func RewardValueIn(vs ...int64) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldIn(FieldRewardValue, vs...))
}

// RewardValueNotIn applies the NotIn predicate on the "reward_value" field.
func RewardValueNotIn(vs ...int64) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNotIn(FieldRewardValue, vs...))
}

// RewardValueGT applies the GT predicate on the "reward_value" field.
func RewardValueGT(v int64) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGT(FieldRewardValue, v))
}

// RewardValueGTE applies the GTE predicate on the "reward_value" field.
func RewardValueGTE(v int64) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGTE(FieldRewardValue, v))
}

// RewardValueLT applies the LT predicate on the "reward_value" field.
func RewardValueLT(v int64) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLT(FieldRewardValue, v))
}

// RewardValueLTE applies the LTE predicate on the "reward_value" field.
func RewardValueLTE(v int64) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLTE(FieldRewardValue, v))
}

// RewardValueIsNil applies the IsNil predicate on the "reward_value" field.
func RewardValueIsNil() predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldIsNull(FieldRewardValue))
}

// RewardValueNotNil applies the NotNil predicate on the "reward_value" field.
func RewardValueNotNil() predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNotNull(FieldRewardValue))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldContainsFold(FieldMessage, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldContainsFold(FieldErrorCode, v))
}

// AttemptCountEQ applies the EQ predicate on the "attempt_count" field.
func AttemptCountEQ(v int) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldAttemptCount, v))
}

// AttemptCountNEQ applies the NEQ predicate on the "attempt_count" field.
func AttemptCountNEQ(v int) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNEQ(FieldAttemptCount, v))
}

// AttemptCountIn applies the In predicate on the "attempt_count" field.
func AttemptCountIn(vs ...int) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldIn(FieldAttemptCount, vs...))
}

// AttemptCountNotIn applies the NotIn predicate on the "attempt_count" field.
func AttemptCountNotIn(vs ...int) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNotIn(FieldAttemptCount, vs...))
}

// AttemptCountGT applies the GT predicate on the "attempt_count" field.
func AttemptCountGT(v int) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGT(FieldAttemptCount, v))
}

// AttemptCountGTE applies the GTE predicate on the "attempt_count" field.
func AttemptCountGTE(v int) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGTE(FieldAttemptCount, v))
}

// AttemptCountLT applies the LT predicate on the "attempt_count" field.
func AttemptCountLT(v int) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLT(FieldAttemptCount, v))
}

// AttemptCountLTE applies the LTE predicate on the "attempt_count" field.
func AttemptCountLTE(v int) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLTE(FieldAttemptCount, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLTE(FieldStartedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNotNull(FieldFinishedAt))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.CheckinRun {
	return predicate.CheckinRun(sql.FieldContainsFold(FieldRequestID, v))
}

// HasSite applies the HasEdge predicate on the "site" edge.
func HasSite() predicate.CheckinRun {
	return predicate.CheckinRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SiteTable, SiteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSiteWith applies the HasEdge predicate on the "site" edge with a given conditions (other predicates).
func HasSiteWith(preds ...predicate.Site) predicate.CheckinRun {
	return predicate.CheckinRun(func(s *sql.Selector) {
		step := newSiteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CheckinRun) predicate.CheckinRun {
	return predicate.CheckinRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CheckinRun) predicate.CheckinRun {
	return predicate.CheckinRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CheckinRun) predicate.CheckinRun {
	return predicate.CheckinRun(sql.NotPredicates(p))
}
